### PR TITLE
fix Armed Intimidation and Malapert Data Vault fixed resolution order

### LINKED ISSUE #5702: Malapert Data Vault + Armed Intimidation - "when you score" forced resolution order
When scoring an Armed Intimidation from a server with _Malapert Data Vault_, the Corp player is forced to resolve _Malapert Data Vault_ first, before the Runner is given the choice between taking 2 tags or taking 5 meat damage.

**Expected Behaviour:** when scoring an agenda with a "when you score" ability (such as _Armed Intimidation_) from a server with _Malapert Data Vault_ installed and rezzed, the Corp player should be able to choose the order of ability resolution.

**Actual Behaviour:** scoring some agendas works as expected, scoring _Armed Intimidation_ forces the order of resolution

Standoff - OK
Hostile Takeover - OK
Armed Initimidation - NOT OK

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #5702

### CODE REVIEW

File: src/clj/game/cards/agendas.clj [hunk 1]
```diff
@@ -175,7 +174,12 @@
                    (do (system-msg state :runner "chooses to take 2 tags from Armed Intimidation")
                        (gain-tags state :runner eid 2 {:card card}))
                    ; else
-                   (effect-completed state side eid)))}})
+                   (effect-completed state side eid)))})]
+    {:on-score
+     {:interactive (req true)
```
Comment (NoahTheDuke) [inline src/clj/game/cards/agendas.clj:179]: I think the only change that's necessary is putting `:interactive true` in the `:on-score` ability. Moving the main ability to a function doesn't actually change anything given that there's no recursion.

**Review by NoahTheDuke — APPROVED** [review]
