### PR TITLE
Bugfix Top Hat interaction with run based cards

### LINKED ISSUE #4542: Tophat and Mad Dash do not work
It seems that the interaction between Top Hat and Mad Dash is broken. When choosing an agenda card using Top Hat, the meat damage fires and the Mad Dash is not added to the runner's score area. This may be that the run is treated as over upon the firing of Top Hat?

### PR DESCRIPTION
**Pull request by lostgeek**
Top Hat wasn't waiting correctly. Closes #4542

### CODE REVIEW

File: src/clj/game/cards/hardware.clj [hunk 1]
```diff
@@ -1555,6 +1555,7 @@
                                    {:card card
                                     :replace-access
                                     {:mandatory true
+                                     :async true
                                      :effect (req (when (empty? (get-cards-to-access state))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/hardware.clj]: Seeing as we're making the ability async, this should be an `if` and the else branch calls `effect-completed`
