### PR TITLE
ADT/Tranquility/Agenda fix

### LINKED ISSUE #6588: Architect Deployment Test and Tranquility Home Grid
When firing the ability of Architect Deployment Test and choosing an Agenda from the top 5 cards of R&D: if you install the Agenda in a Tranquility Home Grid server, you do not initially get the prompt to either Gain 2c or Draw 1 card. The prompt happens after the next click is taken.  (So, if the Corp still has a click left, it's after their click. If the Corp doesn't have a click left, the ability is delayed until the runner takes their first click)

### PR DESCRIPTION
**Pull request by NBKelly**
Installing with `:rez-no-rez-cost` or `:rez-no-cost` wouldn't trigger a checkpoint if you picked an agenda, because `rez` in `rezzing` just completes it's eid if you pick an agenda. 
I added a tiny bit of logic into `installing` that asks "is this an agenda? if so, just trigger the event instead of invoking rez".

Closes #6588

### CODE REVIEW

File: src/clj/game/core/installing.clj [hunk 1]
```diff
@@ -158,15 +158,19 @@
                   (case install-state
                     ;; Ignore all costs
                     :rezzed-no-cost
-                    (rez state side eid moved-card {:ignore-cost :all-costs
-                                                    :no-msg no-msg})
+                    (if-not (agenda? moved-card)
+                      (rez state side eid moved-card {:ignore-cost :all-costs
+                                                      :no-msg no-msg})
+                      (checkpoint state nil (make-eid state eid)))
```
Comment (NoahTheDuke) [inline src/clj/game/core/installing.clj:164]:
```suggestion
                      (checkpoint state nil eid))
```

File: src/clj/game/core/installing.clj [hunk 2]
```diff
@@ -158,15 +158,19 @@
...
                     ;; Ignore rez cost only
                     :rezzed-no-rez-cost
                     (rez state side eid moved-card {:ignore-cost :rez-costs
                                                     :no-msg no-msg})
                     ;; Pay costs
                     :rezzed
-                    (rez state side eid moved-card {:no-msg no-msg})
+                    (if-not (agenda? moved-card)
+                      (rez state side eid moved-card {:no-msg no-msg})
+                      (checkpoint state nil (make-eid state eid)))
```
Comment (NoahTheDuke) [inline src/clj/game/core/installing.clj:173]:
```suggestion
                      (checkpoint state nil eid))
```

File: test/clj/game/cards/upgrades_test.clj [hunk 3]
```diff
@@ -3875,6 +3875,24 @@
           "Runner gained 1 credit from PAD Tap"
           (click-prompt state :corp "Gain 2 [Credits]")))))
 
+(deftest tranquility-home-grid-interaction-with-adt-and-agendas-issue-#6588
```
Comment (NoahTheDuke) [inline test/clj/game/cards/upgrades_test.clj:3878]:
```suggestion
(deftest tranquility-home-grid-interaction-with-adt-and-agendas
```

File: test/clj/game/cards/upgrades_test.clj [hunk 4]
```diff
@@ -3875,6 +3875,24 @@
...
+  ;;check tranquility fires at the right time when installing an agenda and failing to rez it
```
Comment (NoahTheDuke) [inline test/clj/game/cards/upgrades_test.clj:3879]:
```suggestion
  ;;check tranquility fires at the right time when installing an agenda and failing to rez it, issue #6588
```
