### PR TITLE
fix HB: Architects of Tomorrow

### LINKED ISSUE #2035: Jinteki: Potential Unleashed should display which cards the ability trashes
Just makes sense now that you show which cards are trashed via damage.

### LINKED ISSUE #2049: Unable to pass Bioroid ice against HB:AoT with no unrezzed Bioroids in play
Running against Haas Bioroid: Architects of Tomorrow. All ice was rezzed; they were all Bioroids. Attempting to continue past a Bioroid (specifically Vikram 1.0) caused an error in the game state and we were unable to continue until they derezzed an ice.

Stack Trace:
```clojure
Error do continue  #error {
 :cause "Wrong number of args (2) passed to: core/effect-completed"
 :via
 [{:type clojure.lang.ArityException
   :message "Wrong number of args (2) passed to: core/effect-completed"
   :at [clojure.lang.AFn throwArity "AFn.java" 429]}]
 :trace
 [[clojure.lang.AFn throwArity "AFn.java" 429]
  [clojure.lang.AFn invoke "AFn.java" 36]
  [game.core$fn__15947 invokeStatic "identities.clj" 241]
  [game.core$fn__15947 invoke "identities.clj" 229]
  [game.core$do_effect invokeStatic "abilities.clj" 256]
  [game.core$do_effect invoke "abilities.clj" 252]
  [game.core$do_ability invokeStatic "abilities.clj" 237]
  [game.core$do_ability invoke "abilities.clj" 210]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 135]
  [game.core$resolve_ability_eid invoke "abilities.clj" 115]
  [game.core$resolve_ability invokeStatic "abilities.clj" 113]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 48]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync_next$fn__3832 invoke "events.clj" 49]
  [game.core$effect_completed invokeStatic "events.clj" 240]
  [game.core$effect_completed invoke "events.clj" 236]
  [game.core$complete_ability invokeStatic "abilities.clj" 146]
  [game.core$complete_ability invoke "abilities.clj" 140]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 137]
  [game.core$resolve_ability_eid invoke "abilities.clj" 115]
  [game.core$resolve_ability invokeStatic "abilities.clj" 113]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$trigger_event_sync_next invokeStatic "events.clj" 48]
  [game.core$trigger_event_sync_next doInvoke "events.clj" 40]
  [clojure.lang.RestFn applyTo "RestFn.java" 157]
  [clojure.core$apply invokeStatic "core.clj" 654]
  [clojure.core$apply doInvoke "core.clj" 641]
  [clojure.lang.RestFn invoke "RestFn.java" 587]
  [game.core$trigger_event_sync invokeStatic "events.clj" 64]
  [game.core$trigger_event_sync doInvoke "events.clj" 55]
  [clojure.lang.RestFn invoke "RestFn.java" 497]
  [game.core$continue invokeStatic "actions.clj" 385]
  [game.core$continue invoke "actions.clj" 375]
  [game.main$handle_do invokeStatic "main.clj" 77]
  [game.main$handle_do invoke "main.clj" 74]
  [game.main$handle_command invokeStatic "main.clj" 150]
  [game.main$handle_command invoke "main.clj" 139]
  [game.main$run$fn__25013 invoke "main.clj" 185]
  [game.main$run invokeStatic "main.clj" 175]
  [game.main$run invoke "main.clj" 169]
  [game.main$_main$fn__25048 invoke "main.clj" 239]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 745]]}
```

### PR DESCRIPTION
**Pull request by JoelCFC25**
* Fixes #2049: Missing function argument causing an error when Runner passes a bioroid and there are no unrezzed bioroids.
* Fixes #2035: Reveal the card milled by Jinteki: Potential Unleashed
* Fix wrong message for Mausolus credit gain subroutine

Ignore failing test, getting fixed at #2048.

### CODE REVIEW

File: src/clj/game/cards/identities.clj [hunk 1]
```diff
@@ -333,9 +333,12 @@
              :agenda-stolen {:msg "do 1 net damage" :effect (effect (damage eid :net 1 {:card card}))}}}
 
    "Jinteki: Potential Unleashed"
-   {:events {:pre-resolve-damage {:req (req (and (= target :net) (> (last targets) 0)))
-                                  :msg "trash the top card of the Runner's Stack"
-                                  :effect (effect (mill :runner))}}}
+   {:events {:pre-resolve-damage
+             {:req (req (and (= target :net) (> (last targets) 0)))
```
Comment (Saintis) [inline src/clj/game/cards/identities.clj]: Should be `pos?` 😛

**Comment by mtgred** [comment]
👍
