### PR TITLE
PRIORITY: fix HQ access with rezzed upgrades;  implement CBI Raid

### LINKED ISSUE #1332: Mumbad Construction Corp + Dedication Ceremony
When you use Dedication Ceremony on Mumbad Construction Corp and then move the tokens you just put onto a new agenda, Jnet refuses to let you score the agenda that turn. Presumably it links the DC "can't-score" status to the advancement counters instead of the card given those counters.

### LINKED ISSUE #1333: gabe and crisium grid
hello opponent had crisium grid installed in hq, i had gabe with security testing, john masonori, and can't recall if desperado. when ran hq, asked to access cris or hand, clicked crisium grid and something like an infinite list of unrezzed card in hq came up. thank you

### LINKED ISSUE #1334: Lakshmi SmartFabrics
Hi, first of all, I'd like to thank you for being so dedicated to Jinteki.net. You guys are great!

Moving on to the issue, I just finished up a game as Gagarin with two Lakshmi Smartfabrics on the board, one with 9 counters, one with 7, and I could use neither of them on the runner's turn to prevent them from accessing Project Atlas in a remote. I had Ice Wall and Project Atlas in hand ( 
ejwgdju
 ) and Atlas is worth 2 points, so I think this might be a bug. 

Clicking Lakshmi and selecting "Spend X counters" didn't change the state, including the removal of counters. 

Thanks for taking a look at this!

### PR DESCRIPTION
**Pull request by JoelCFC25**
The access helper function for HQ has a bunch of problems from @nealterrell's work on getting Leela bounce w/ multiaccess working. He diagnosed it in chat this afternoon. This could also potentially take care of #1325 and #1247, but we'll have to wait and see.  

CBI Raid is fairly straightforward--decided to give the Runner a wait prompt that's only cleared when the Corp signals they're done putting everything from their hand onto R&D. 

Fixes #1332, fixes #1333, fixes #1334. Dedication Ceremony had a turn-flag that was too broad--preventing *any* agenda from being scored that turn, even if it was not the card targeted by the operation. Added a few small Business First touchups: New Construction shouldn't be able to install ICE, Lakshmi gets a counter for rezzing itself and had an agenda targeting goof, Product Recall needs to factor in trash cost modifiers, Mr. Li missing event trigger to combo with Palana Foods.

### CODE REVIEW

File: src/clj/game/cards-identities.clj [hunk 1]
```diff
@@ -370,7 +370,8 @@
                               :req (req (has-subtype? target "Virus"))}}}
 
    "Pālanā Foods: Sustainable Growth"
-   {:events {:runner-draw {:msg "gain 1 [Credits]"
+   {:events {:runner-draw {:req (req (not= 0 (:turn @state)))
```
Comment (zaroth) [inline src/clj/game/cards-identities.clj]: I don't think putting an exception for mulligan turn is the right approach. It'd probably be more desirable to make mulligan draws not trigger any effects, since taking new cards due to mulligan isn't really a draw in normally used game terms.

Comment (JoelCFC25) [inline src/clj/game/cards-identities.clj]: So maybe a `take`, `doseq` and `move` in the mulligan function then?

**Comment by mtgred** [comment]
:+1:
