### PR TITLE
Fix Keiko trigger condition (supersedes #5900 )

### LINKED ISSUE #5892: Keiko triggers twice if a companion is installed and used in the same turn
Specifically, it triggered when I installed a paladin poemu and again when I ran and used trickster taka credits later in the turn - it should only trigger the first time either condition is met, not the first time a companion is installed and the first time credits from a companion are used.
image

### PR DESCRIPTION
**Pull request by h4pp7**
I realized that thehead branch for my pull request #5900 was my master branch, which was a bit annoying. I made a new branch and this new pull request. Sorry for that!

Original message:
Fixes #5892 

Keiko gave credits a second time in a turn, when credits where used from
a companion after a companion was installed that turn.

`event-count` with `:runner-install` now gets a different filter
predicate than the call with `:spent-credits-from-card`.

### CODE REVIEW

File: src/clj/game/cards/hardware.clj [hunk 1]
```diff
@@ -942,10 +942,12 @@
...
                             (has-subtype? target "Companion")
-                            (let [f #(and (not (facedown? (first %)))
-                                          (has-subtype? (first %) "Companion"))]
-                              (= 1 (+ (event-count state :runner :spent-credits-from-card f)
-                                      (event-count state :runner :runner-install f))))))
+                            (= 1 (+ (event-count state :runner :spent-credits-from-card
+                                                 #(and (not (facedown? (first %)))
+                                                       (has-subtype? (first %) "Companion")))
+                                    (event-count state :runner :runner-install
+                                                 #(and (not (:facedown (first %)))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/hardware.clj:949]:
```suggestion
                                                 #(and (not (facedown? (first %)))
```

Comment (NoahTheDuke) [reply src/clj/game/cards/hardware.clj:949]: jk not this one
