### PR TITLE
FIX: Maya regression

### LINKED ISSUE #3493: Maya steal-trigger-events unbound
Looks like this function disappeared in one of @NoahTheDuke trash PRs.

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Fixes #3493, updates test to check against agenda.

### CODE REVIEW

File: src/clj/game/cards/hardware.clj [hunk 1]
```diff
@@ -552,29 +552,30 @@
...
                                 (when-completed (tag-runner state :runner (make-eid state) 1)
                                                 (close-access-prompt state side))))}
                 {:once :per-turn
                  :label "Move a previously accessed card to bottom of R&D"
                  :effect (effect (resolve-ability
-                                   {; only allow targeting cards that were accessed this turn -- not perfect, but good enough?
-                                    :delayed-completion true
-                                    :choices {:req #(some (fn [c] (= (:cid %) (:cid c)))
+                                   {:delayed-completion true
+                                    ; only allow targeting cards that were accessed this turn
```
Comment (Saintis) [inline src/clj/game/cards/hardware.clj]: This comment should start with `;;` since it's on a separate line.

Comment (NoahTheDuke) [reply src/clj/game/cards/hardware.clj]: Good call.
