### PR TITLE
fix Checkpoint dealing damage at the end of a successful run

### LINKED ISSUE #6166: Checkpoint (card) deals meat damage after successful run ends instead of when the run becomes successful
I unfortunately didn't have game recorded, but this is the log of the relevant turn:

```
ThatsNoMun spends  to make a run on Server 1.
ThatsNoMun approaches ice protecting Server 1 at position 1.
Paksenarrion pays 4  to rez Checkpoint.
Paksenarrion takes 1 bad publicity from Checkpoint.
Paksenarrion has no further action.
ThatsNoMun encounters Checkpoint protecting Server 1 at position 1.
ThatsNoMun indicates to fire all unbroken subroutines on Checkpoint.
Paksenarrion uses Checkpoint to initiate a trace with strength 5 (Do 3 meat damage when this run is successful).
Paksenarrion pays 3  to increase trace strength to 8.
ThatsNoMun pays 0  to increase link strength to 0.
The trace was successful.
Paksenarrion uses Checkpoint to do 3 meat damage when this run is successful.
Paksenarrion resolves 1 unbroken subroutine on Checkpoint (" Trace 5 - Do 3 meat damage when this run is successful").
ThatsNoMun has no further action.
ThatsNoMun passes Checkpoint protecting Server 1 at position 1.
ThatsNoMun approaches Veritas protecting Server 1 at position 0.
ThatsNoMun encounters Veritas protecting Server 1 at position 0.
ThatsNoMun pays 2  to install MKUltra.
ThatsNoMun pays 3  to use MKUltra to increase its strength from 1 to 3.
ThatsNoMun to use MKUltra to break 2 Sentry subroutines on Veritas (" Runner loses 2 " and " Trace 2 - Give the Runner 1 tag").
ThatsNoMun indicates to fire all unbroken subroutines on Veritas.
ThatsNoMun has no further action.
Paksenarrion uses Veritas to gain 2 .
Paksenarrion resolves 1 unbroken subroutine on Veritas (" Corp gains 2 ").
ThatsNoMun passes Veritas protecting Server 1 at position 0.
ThatsNoMun will continue the run.
ThatsNoMun approaches Server 1.
ThatsNoMun uses Knobkierie to place 1 virus counter on Imp.
ThatsNoMun breaches Server 1.
ThatsNoMun accesses Clearinghouse from Server 1.
ThatsNoMun spends 1 hosted virus counter from on Imp to use Imp to trash Clearinghouse at no cost.
ThatsNoMun uses René "Loup" Arcemont: Party Animal to gain 1  and draw 1 card.
ThatsNoMun uses Consume to place 1 virus counter on Consume.
Paksenarrion uses Checkpoint to do 3 meat damage.
ThatsNoMun trashes Liberated Account, Fermenter, Rezeki due to meat damage.
ThatsNoMun spends  to use Runner Basic Action Card to draw 1 card.
ThatsNoMun spends  to use Runner Basic Action Card to draw 1 card.
ThatsNoMun is ending their turn 12 with 10  and 4 cards in their Grip.
```

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6166

### CODE REVIEW

File: test/clj/game/cards/ice_test.clj [hunk 1]
```diff
@@ -850,6 +850,38 @@
...
+        (fire-subs state chckpnt)
+        (click-prompt state :corp "0")
+        (click-prompt state :runner "0")
+        (run-continue state)
+        (run-continue state)
+        (is (prompt-map :runner) "Still have access prompt")
+        (is (= 3 (count (:discard (get-runner)))) "Runner suffered 3 meat damage")
+        (click-prompt state :runner "No action")
+        (is (not (:run @state)) "Run is finished")
+      )))
```
Comment (NoahTheDuke) [inline test/clj/game/cards/ice_test.clj:883]: 👀
