### PR TITLE
Fix Paperclip double charging

### LINKED ISSUE #5395: Breaking 4 advanced Akhet with paperclip takes twice the credit cost from runner bank
Run Akhet with 3 advancements, so str 5
Runner has 12 credits
Break Akhet for 4 with paperclip
Runner credit total goes to 4 credits

If you have 5 credits, breaking for 4 puts you on 1 credit but the 'which subs do you want to break' prompt doesn't appear.

### PR DESCRIPTION
**Pull request by jwarwick**
Fixes #5395

### CODE REVIEW

File: test/clj/game/cards/programs_test.clj [hunk 1]
```diff
@@ -3659,7 +3659,30 @@
...
+        (changes-val-macro
+          -2 (:credit (get-runner))
+          "Paid 2 to break two of the subs on Hive"
+          (is (= 5 (count (:subroutines (get-ice state :hq 0)))) "Hive starts with 5 subs")
+          (is (= 3 (core/get-strength (get-ice state :hq 0))) "Hive has strength 3")
+          (card-ability state :runner pc 0)
+          (click-prompt state :runner "2")
+          (click-prompt state :runner "End the run")
+          (click-prompt state :runner "End the run")
+          (is (= 3 (core/get-strength (refresh pc))) "Pumped Paperclip up to str 3")
```
Comment (NoahTheDuke) [inline test/clj/game/cards/programs_test.clj:3684]: don't have to use `core/` for `get-strength`, cuz i re-exported it in `core_test`

File: src/clj/game/cards/programs.clj [hunk 2]
```diff
@@ -1860,17 +1860,19 @@
...
-                                  :heap-breaker-break :x ; number of subs broken
-                                  :effect (effect (continue-ability
-                                                    (pump-and-break [:credit (cost-value eid :x-credits)]
-                                                                    (cost-value eid :x-credits)
-                                                                    "Barrier")
-                                                    card nil))}])]
-    (assoc cdef :events (apply conj events (:events cdef)))))
+        cdef (install-from-heap "Paperclip" "Barrier" [])
+        abilities [{:label "+X strength, break X subroutines"
+                           :cost [:x-credits]
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:1865]: looks like spacing got messed up here

File: src/clj/game/cards/programs.clj [hunk 3]
```diff
@@ -1860,17 +1860,19 @@
...
+                           :heap-breaker-pump :x ; strength gained
+                           :heap-breaker-break :x ; number of subs broken
+                           :pump :x
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:1868]: `:pump` generally expects a number, but is only used for the auto-pump-and-break stuff. Should we even be including it here?
