### PR TITLE
Small fixes (EBC, Reverse Infection, Searchlight, Herald)

### LINKED ISSUE #3892: Firing Herald's 2nd sub leave "waiting for Corp" prompt on Runner's side
Yeah, I played with Herald. And it did some work. A little bit of work. It's probably better as a different ice...

### LINKED ISSUE #4200: Searchlight chat text
In rare circumstances, you can meet a Searchlight out there in Weylandia. Unfortunately, the chat message is a weirdo.
searchlight

### LINKED ISSUE #4202: Reverse Infection doesn't account for viruses on corp cards
Viruses on corp cards (eg. [Sandstone](https://netrunnerdb.com/en/card/26059)) aren't counted when milling  cards from [Reverse Infection](https://netrunnerdb.com/en/card/21053) purge

### LINKED ISSUE #4204: Executive Bootcamp and Slot Machine reveals don't trigger Hyoubu
I'm reasonably sure they ought to, but the Hyoubu automation doesn't pick them up. It's not too hard to fix manually, but it means you have to explain why you're adding credits off-turn to your opponent. It might just be that Hyoubu isn't seeing reveal effects that happen on the Runner turn.

### PR DESCRIPTION
**Pull request by kevkcc**
Closes #4204
Closes #4202 
Closes #4200
Closes #3892

### CODE REVIEW

File: test/clj/game_test/cards/operations.clj [hunk 1]
```diff
@@ -1890,26 +1890,33 @@
...
+      (play-from-hand state :corp "Reverse Infection")
+      (click-prompt state :corp "Gain 2 [Credits]")
+      (is (= 7 (:credit (get-corp))) "Corp gained 2 credits")))
+  (testing "Purge virus counters, counts both Runner and Corp side (Sandstone)")
   (do-game
-    (new-game {:corp {:deck [(qty "Reverse Infection" 2)]}
-               :runner {:deck ["Virus Breeding Ground" "Datasucker" (qty "Sure Gamble" 3)]}})
+    (new-game {:corp {:deck ["Reverse Infection" "Sandstone"]}
+               :runner {:deck ["Virus Breeding Ground" "Datasucker" (qty "Sure Gamble" 4)]}})
     (starting-hand state :runner ["Virus Breeding Ground" "Datasucker"])
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/operations.clj]: This can be written in the `new-game` hash: `:runner {:deck [...] :hand ["Virus Breeding Ground" "Datasucker"]}`

Comment (kevkcc) [reply test/clj/game_test/cards/operations.clj]: Sweet, learn something new all the time. I wonder if we should just go through and change all cards that use `(starting-hand [...])` to this better way?

Comment (NoahTheDuke) [reply test/clj/game_test/cards/operations.clj]: I've thought about it! Just a tedious piece of work for relatively little gain, lol.

**Comment by NoahTheDuke** [comment]
Could you pass a `req` to choices to build the list of Herald numbers, returning `(min 2 (:credit corp))`?

**Comment by NoahTheDuke** [comment]
I wonder why Circle isn't picking up this branch? I'd love to see the test results

**Comment by kevkcc** [comment]
Yea I don't know actually. "It works on my computer....." 👍
