### PR TITLE
install and install-free commands

### LINKED ISSUE #5009: Enforce rules in more cases and add "Fix board state" mode
Since we're more and more approaching full rules coverage in the jnet interface, we could start thinking about removing the last bits and pieces of "freedom" outside the rules. There are cases like installing programs mid-run from hand, which we still allow to make fixing the board state easier once something does go wrong.

We could now think about a fix board state mode (indicated by `(:fix-board-state @state)`), which is indicated clearly in the UI and releases some actions that were previously prevented by the rules (jacking out during a run / installing things from hand / using the +- buttons on clicks, credits, etc.).

### PR DESCRIPTION
**Pull request by NBKelly**
If we're going to disallow installing from hand while prompts are up, we should allow a way to fix gamestates if they're broke - so these commands will do.

Closes #5009, in concert with #7498

### CODE REVIEW

File: src/clj/game/core/commands.clj [hunk 1]
```diff
@@ -209,6 +209,28 @@
...
+        :choices {:card #(and (corp? %)
+                              (not (installed? %)))}
+        :async true
+        :effect (req (corp-install state side eid target nil {:ignore-all-cost ignore-all-cost}))}
+       {:prompt (str "Choose a card to install" (when ignore-all-cost " (ignoring all costs)"))
+        :choices {:card #(and (runner? %)
+                              (not (installed? %)))}
+        :async true
+        :effect (req (runner-install state side eid target {:ignore-all-cost ignore-all-cost}))})
+     nil nil)))
```
Comment (NoahTheDuke) [inline src/clj/game/core/commands.clj:228]:
```suggestion
     (make-card {:title (str "/install" (when ignore-all-cost "-free") " command")}) nil)))
```
