### PR TITLE
Data Ward fix and new tests

### LINKED ISSUE #4965: Data Ward Hanging Prompt
If you pay 3 on data ward, the prompt "Waiting for Corp to resolve encounter-ice triggers" appears and doesn't go away unless you use close-prompt.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4965

Fix and new tests.

### CODE REVIEW

File: src/clj/game/cards/ice.clj [hunk 1]
```diff
@@ -978,7 +978,8 @@
                   :async true
                   :effect (req (if (= target "Pay 3 [Credits]")
                                  (do (system-msg state :runner "pays 3 [Credits]")
-                                     (pay-sync state :runner card eid :credit 3))
+                                     (pay-sync state :runner card eid :credit 3)
+                                     (effect-completed state side eid))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/ice.clj]: If this is needed, something more complex is broken, because the `eid` in the `pay-sync` call should be calling `effect-completed` for us.

Comment (NoahTheDuke) [reply src/clj/game/cards/ice.clj]: Oh duh, the arguments are backwards.

File: src/clj/game/cards/ice.clj [hunk 2]
```diff
@@ -978,7 +978,8 @@
                   :async true
                   :effect (req (if (= target "Pay 3 [Credits]")
                                  (do (system-msg state :runner "pays 3 [Credits]")
-                                     (pay-sync state :runner card eid :credit 3))
+                                     (pay-sync state :runner card eid :credit 3)
```
Comment (NoahTheDuke) [inline src/clj/game/cards/ice.clj]:
```suggestion
                                     (pay-sync state :runner eid card :credit 3)
```
