### PR TITLE
Fix ping on-rez ability

### LINKED ISSUE #5730: Ping tags the runner if rezzed during a run on a different server (e.g. Send a Message)
If a Ping on a server other than the attacked server is rezzed during a run, (in this case a Ping on HQ rezzed because the runner stole a Send A Message from R&D) it will still tag the runner.

### PR DESCRIPTION
**Pull request by merrickbrown**
Ping's on-rez ability now checks that the run is against the server it is installed in. Fixes #5730

### CODE REVIEW

File: src/clj/game/cards/ice.clj [hunk 1]
```diff
@@ -2672,7 +2672,7 @@
    :strength-bonus (req (if (wonder-sub card 3) 5 0))})
 
 (defcard "Ping"
-  {:on-rez {:req (req run)
+  {:on-rez {:req (req (= (first (:server run)) (second (get-zone card))))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/ice.clj:2675]:
```suggestion
  {:on-rez {:req (req (and run this-server))
```
