### PR TITLE
fixed SMC price

### LINKED ISSUE #4961: SMC + Recurring Credits
When you fire SMC, you should be able to use recurring credits (e.g. Multithreader) to pay for firing the program BEFORE you have to pay for the program you are searching for.

Right now, if you try and fire Multithreader with $2 in your credit pool and a Multithreader, you cannot search for and install a Rezeki.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4961

Implementation and new test case.

### CODE REVIEW

File: src/clj/game/cards/programs.clj [hunk 1]
```diff
@@ -2335,10 +2335,9 @@
                                                (str "shuffle their Stack")))
                                    :choices (req (conj (filter #(can-pay? state side
                                                                           (assoc eid :source card :source-type :runner-install)
-                                                                          % nil [:credit (install-cost state side % {:cost-bonus 2})])
+                                                                          % nil [:credit (install-cost state side % )])
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj]:
```suggestion
                                                                          % nil [:credit (install-cost state side %)])
```

**Comment by Kubik161** [comment]
Closes also #4993
