### PR TITLE
Major refactor of costs, fix cost strings to only print "Pay" when necessary

### LINKED ISSUE #4316: build-cost-str strings are broken
image

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Closes #4316

### CODE REVIEW

File: src/clj/game/core/costs.clj [hunk 1]
```diff
@@ -145,38 +149,151 @@
...
+      (str (build-cost-label cost) ": " label)
+      label)))
+
+(let [cost-types #{:trash
+                   :hardware :program :resource :connection :ice
+                   :net :meat :brain
+                   :trash-from-deck :trash-from-hand :randomly-trash-from-hand
+                   :agenda :power :virus :advancement
+                   :forfeit :shuffle-installed-to-stack}]
+  (defn cost->string
```
Comment (lostgeek) [inline src/clj/game/core/costs.clj]: Maybe swap `defn` and `let`?

Comment (NoahTheDuke) [reply src/clj/game/core/costs.clj]: I wrote it like this because I don't want to recreate the `cost-types` set every call to `cost->string`, as it's static, but I also don't want to `def` it into a namespace-global variable, because that's messy. Doing the `let` binding around the `defn` means that it'll only be created once, and only this function will have access to it.

Comment (NoahTheDuke) [reply src/clj/game/core/costs.clj]: Decided to reverse this logic, so it's not even needed anymore!
