### PR TITLE
faq 4.1 changes & fixes

### LINKED ISSUE #2412: Decked before starting.
Started a game, the display was wonky and I couldn't start. And I also "lost" because I was decked before beginning.

image

### LINKED ISSUE #2894: Punitive Counterstrike/Hades Shard interaction
Punitive Counterstrike takes into account agenda points from agendas stolen during Corporation's current turn (for example by pulling agendas out of archives with Hades Shard). This is against the rules (PC only cares for points stolen during the Runner's last turn.)

### LINKED ISSUE #2904: Ikawah Project Button to pay click causes server error
Please describe the circumstances of your error here.

Stack Trace:
```clojure
Error do choice [Click] #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Numbers ops "Numbers.java" 1013]}]
 :trace
 [[clojure.lang.Numbers ops "Numbers.java" 1013]
  [clojure.lang.Numbers add "Numbers.java" 128]
  [game.utils$merge_costs$fn__51 invoke "utils.clj" 30]
  [clojure.core.protocols$fn__6755 invokeStatic "protocols.clj" 167]
  [clojure.core.protocols$fn__6755 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__6710$G__6705__6719 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__6738 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__6738 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__6684$G__6679__6697 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6545]
  [clojure.core$reduce invoke "core.clj" 6527]
  [game.utils$merge_costs invokeStatic "utils.clj" 29]
  [game.utils$merge_costs invoke "utils.clj" 21]
  [game.core$can_pay_QMARK_ invokeStatic "costs.clj" 41]
  [game.core$can_pay_QMARK_ doInvoke "costs.clj" 36]
  [clojure.lang.RestFn invoke "RestFn.java" 467]
  [game.core$steal_pay_choice$fn__6724 invoke "runs.clj" 172]
  [game.core$do_effect invokeStatic "abilities.clj" 260]
  [game.core$do_effect invoke "abilities.clj" 256]
  [game.core$do_ability invokeStatic "abilities.clj" 241]
  [game.core$do_ability invoke "abilities.clj" 214]
  [game.core$resolve_ability_eid invokeStatic "abilities.clj" 136]
  [game.core$resolve_ability_eid invoke "abilities.clj" 113]
  [game.core$resolve_ability invokeStatic "abilities.clj" 111]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$resolve_ability invokeStatic "abilities.clj" 109]
  [game.core$resolve_ability invoke "abilities.clj" 38]
  [game.core$prompt_BANG_$fn__6154 invoke "abilities.clj" 309]
  [game.core$resolve_prompt invokeStatic "actions.clj" 150]
  [game.core$resolve_prompt invoke "actions.clj" 120]
  [game.main$handle_do invokeStatic "main.clj" 83]
  [game.main$handle_do invoke "main.clj" 79]
  [game.main$handle_command invokeStatic "main.clj" 152]
  [game.main$handle_command invoke "main.clj" 141]
  [game.main$run$fn__32217 invoke "main.clj" 201]
  [game.main$run invokeStatic "main.clj" 191]
  [game.main$run invoke "main.clj" 184]
  [game.main$_main$fn__32254 invoke "main.clj" 260]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 748]]}
```

### LINKED ISSUE #2910: Gauntlet + Sneakdoor Beta
Combo allows additional accesses from HQ for each piece of ice on archives that a broken by the runner. Is this intended?

### LINKED ISSUE #2925: Mr. Stone and the Cleaners
Mr. Stone is consistently not triggering the extra damage from a scored The Cleaners

### LINKED ISSUE #2934: Shard(s) install windows not suppressing access
Hello,

When the runner has any of the shards in hand, there is no window between "successful run" and "access" in which they can install the shards. The system seems to allow them to install BEFORE clicking successful run without paying the install cost or a credit, but it doesn't then stop the access.

I've tested this with all three shards (Utopia Shard, Eden Shard, and Hades Shard)

Thanks,
Brendan

### LINKED ISSUE #2938: IQ doesn't apply rez cost increase when targeted by Brute Force Hack
Brute Force Hack was played targeting IQ (with 4 cards in hand), and the system charged 0c for the de-rez rather than 4.

### LINKED ISSUE #2946: Fix bad positioning for X in win pop-up

### LINKED ISSUE #2949: Executives trashed when Worlds Plaza is trashed go into Runner's score area
The Board, Victoria Jenkins, Director Haas, and Chairman Hiro read "if the runner trashes while accessing, add to the runner's score area as an agenda worth 2 points". If they are hosted on Worlds Plaza, and the runner accesses and trashes Worlds Plaza but not the executives individually, they currently still go into the score area when trashed. They should go into Archives. Hope this is fixable and I'm not wrong about the technicality here!

### LINKED ISSUE #2956: Adjusted Chronotype & MCA Austerity Policy
Adjusted Chronotype does not fire when the runner loses a click at start of turn from the MCA Austerity Policy paid ability.

### LINKED ISSUE #2957: Gang Sign Inappropriately Accessing Multiple Cards from HQ
AOT scored a CST while Leela had 2 Gang Sign. Each GS accessed 2 cards; no HQ Interface was installed.

Game Log follows (skip to the end for incident; Runner conceded due to extra accesses)

2woke2smoke
glgl
Capslock Intern keeps their hand.
2woke2smoke keeps their hand.

Capslock Intern
you too
Capslock Intern started their turn 1 with 5  and 5 cards in HQ.
Capslock Intern spends  to install ICE protecting R&D.
Capslock Intern spends  to gain 1 .
Capslock Intern spends  to gain 1 .
Capslock Intern is ending their turn 1 with 7  and 5 cards in HQ.
2woke2smoke started their turn 1 with 5  and 5 cards in their Grip.
Oldem joined the game as a spectator.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 5  to play Sure Gamble.
2woke2smoke uses Sure Gamble to gain 9 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Daily Casts.
2woke2smoke is ending their turn 1 with 6  and 5 cards in their Grip.
Capslock Intern started their turn 2 with 7  and 5 cards in HQ.
Capslock Intern spends  and 1 to play Special Report.
Capslock Intern uses Special Report to shuffle 3 cards in HQ into R&D and draw 3 cards.
Capslock Intern spends  to gain 1 .
Capslock Intern spends  to gain 1 .
Capslock Intern is ending their turn 2 with 8  and 5 cards in HQ.
2woke2smoke started their turn 2 with 6  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke accesses Fairchild from HQ.
2woke2smoke spends  and 1  to install Gang Sign.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke is ending their turn 2 with 9  and 4 cards in their Grip.
Capslock Intern started their turn 3 with 8  and 5 cards in HQ.
Capslock Intern spends  and 5 to play Hedge Fund.
Capslock Intern uses Hedge Fund to gain 9 .
Capslock Intern spends  to install ICE protecting Server 1 (new remote).
Capslock Intern spends  to install a card in Server 1.
Capslock Intern is ending their turn 3 with 12  and 3 cards in HQ.
2woke2smoke started their turn 3 with 9  and 4 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Daily Casts.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 3 with 7  and 4 cards in their Grip.
Capslock Intern uses Museum of History to shuffle Hedge Fund into R&D.
Capslock Intern started their turn 4 with 11  and 3 cards in HQ.
Capslock Intern spends  to install ICE protecting HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 8 to play IPO.
Capslock Intern uses IPO to gain 13 .
Capslock Intern is ending their turn 4 with 16  and 3 cards in HQ.
2woke2smoke started their turn 4 with 7  and 4 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install Aumakua.
2woke2smoke spends  to draw a card.
2woke2smoke discards Daredevil from their Grip.
2woke2smoke is ending their turn 4 with 8  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle IPO into R&D.
Capslock Intern started their turn 5 with 16  and 3 cards in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to install ICE protecting Archives.
Capslock Intern is ending their turn 5 with 16  and 5 cards in HQ.
2woke2smoke started their turn 5 with 8  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  and 1  to play Peace in Our Time.
2woke2smoke uses Peace in Our Time to gain 10 . The Corp gains 5 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to install Dean Lister.
2woke2smoke is ending their turn 5 with 19  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle Special Report into R&D.
Capslock Intern started their turn 6 with 21  and 5 cards in HQ.
Capslock Intern spends  to install a card in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern is ending their turn 6 with 21  and 5 cards in HQ.
2woke2smoke started their turn 6 with 19  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to install The Turning Wheel.
2woke2smoke spends  and 3  to install GPI Net Tap.
2woke2smoke is ending their turn 6 with 16  and 5 cards in their Grip.
Capslock Intern started their turn 7 with 21  and 5 cards in HQ.
Capslock Intern spends  and 1 to install ICE protecting R&D.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 8 to play IPO.
Capslock Intern uses IPO to gain 13 .
Capslock Intern is ending their turn 7 with 25  and 5 cards in HQ.
2woke2smoke started their turn 7 with 16  and 5 cards in their Grip.
2woke2smoke uses Daily Casts to gain 2 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 2  to play Deuces Wild.
2woke2smoke uses Deuces Wild to draw 2 cards.
2woke2smoke uses Deuces Wild to expose 1 ice and make a run.
2woke2smoke exposes Fairchild 2.0 protecting Archives at position 0.
2woke2smoke exposes Fairchild 2.0 protecting Archives at position 0.
Capslock Intern spends 4  to rez Fairchild 2.0.
2woke2smoke uses Dean Lister to add +1 strength for each card in their Grip to Aumakua until the end of the run.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke indicates to fire the "Force the Runner to pay 2  or trash an installed card" subroutine on Fairchild 2.0.
Capslock Intern uses Fairchild 2.0 to force the Runner to pay 2  or trash an installed card.
Capslock Intern uses Fairchild 2.0 to force the Runner to trash Cache.
Capslock Intern has no further action.
Capslock Intern uses Haas-Bioroid: Architects of Tomorrow to rez Ravana 1.0.
Capslock Intern rezzes Ravana 1.0.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke spends  and 2  to install Dean Lister.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 7 with 11  and 5 cards in their Grip.
Capslock Intern uses Museum of History to shuffle IPO into R&D.
Capslock Intern started their turn 8 with 21  and 5 cards in HQ.
Capslock Intern spends  to install ICE protecting Server 2 (new remote).
Capslock Intern moves a card from their Server 2 to HQ.
Capslock Intern sets click to 3 (+1).
Capslock Intern spends  to install ICE protecting Server 3 (new remote).
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  to draw a card.
Capslock Intern is ending their turn 8 with 21  and 5 cards in HQ.
2woke2smoke started their turn 8 with 11  and 5 cards in their Grip.
2woke2smoke spends  and 2  to play Deuces Wild.
2woke2smoke uses Deuces Wild to draw 2 cards.
2woke2smoke uses Deuces Wild to gain 3 .
2woke2smoke spends  and 5  to play Sure Gamble.
2woke2smoke uses Sure Gamble to gain 9 .
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 1  to install Au Revoir.
2woke2smoke is ending their turn 8 with 15  and 5 cards in their Grip.
Capslock Intern started their turn 9 with 21  and 5 cards in HQ.
Capslock Intern spends  to install a card in Server 3.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern trashes Museum of History in Server 1.
Capslock Intern spends 1  to rez MCA Austerity Policy.
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern is ending their turn 9 with 20  and 4 cards in HQ.
2woke2smoke started their turn 9 with 15  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to play On the Lam.
2woke2smoke hosts On the Lam on Gang Sign.
2woke2smoke spends  to draw a card.
2woke2smoke discards Aumakua from their Grip.
2woke2smoke is ending their turn 9 with 12  and 5 cards in their Grip.
Capslock Intern spends 2  to rez Marilyn Campaign.
Capslock Intern started their turn 10 with 18  and 4 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  and 5 to play Hedge Fund.
Capslock Intern uses Hedge Fund to gain 9 .
Capslock Intern spends 2  to rez Awakening Center.
Capslock Intern spends  to use Awakening Center to host a piece of Bioroid ICE.
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern is ending their turn 10 with 22  and 3 cards in HQ.
2woke2smoke started their turn 10 with 12  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 3  to install The Supplier.
2woke2smoke spends  to use The Supplier to host Daredevil.
2woke2smoke is ending their turn 10 with 9  and 4 cards in their Grip.
Capslock Intern started their turn 11 with 22  and 3 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  to use MCA Austerity Policy to to force the Runner to lose a  next turn and place a power counter on itself.
Capslock Intern spends  to use MCA Austerity Policy to gain 4 and trash itself.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern gains 4  from CFC Excavation Contract.
Capslock Intern scores CFC Excavation Contract and gains 2 agenda points.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Viktor 1.0 from HQ.
2woke2smoke uses Leela Patel: Trained Pragmatist to add ICE protecting HQ at position 0 to HQ.
Capslock Intern is ending their turn 11 with 24  and 4 cards in HQ.
2woke2smoke started their turn 11 with 9  and 4 cards in their Grip.
2woke2smoke spends 3  to install Daredevil.
2woke2smoke uses The Supplier to install Daredevil lowering its install cost by 2.
2woke2smoke spends  to make a run on HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke jacks out.
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke jacks out.
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke uses Au Revoir to gain 1 .
2woke2smoke spends  to make a run on HQ.
Capslock Intern has no further action.
2woke2smoke uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
2woke2smoke accesses Fairchild 2.0 from HQ.
2woke2smoke accesses Viktor 1.0 from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke is ending their turn 11 with 12  and 4 cards in their Grip.
Capslock Intern started their turn 12 with 24  and 4 cards in HQ.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern spends  to install ICE protecting HQ.
Capslock Intern spends  and 1 to install ICE protecting HQ.
Capslock Intern spends  to draw a card.
Capslock Intern is ending their turn 12 with 25  and 4 cards in HQ.
2woke2smoke started their turn 12 with 12  and 4 cards in their Grip.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke spends  and 4  to install Sneakdoor Beta.
2woke2smoke trashes Cache from their Rig.
2woke2smoke spends  to use Sneakdoor Beta to make a run on Archives.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
Capslock Intern has no further action.
Capslock Intern uses Haas-Bioroid: Architects of Tomorrow to rez Fairchild 2.0.
Capslock Intern rezzes Fairchild 2.0.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke uses Sneakdoor Beta to make a successful run on HQ.
2woke2smoke accesses Museum of History from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke spends  to use Sneakdoor Beta to make a run on Archives.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
2woke2smoke spends 1  to use Aumakua to break 1 subroutine.
Capslock Intern has no further action.
2woke2smoke continues the run.
Capslock Intern has no further action.
2woke2smoke uses The Turning Wheel to access 1 additional card from HQ or R&D for the remainder of the run.
2woke2smoke uses Sneakdoor Beta to make a successful run on HQ.
2woke2smoke accesses Howler from HQ.
2woke2smoke accesses Museum of History from HQ.
2woke2smoke pays 3  to trash Museum of History from HQ.
2woke2smoke accesses Awakening Center from the root of HQ.
2woke2smoke places a power counter on The Turning Wheel.
2woke2smoke is ending their turn 12 with 1  and 2 cards in their Grip.
Capslock Intern uses Marilyn Campaign to gain 2 .
Capslock Intern uses Marilyn Campaign to shuffle it back into R&D.
Capslock Intern started their turn 13 with 27  and 3 cards in HQ.
Capslock Intern spends  to draw a card.
Capslock Intern spends  to draw a card.
Capslock Intern spends  and 1 to install ICE protecting Archives.
Capslock Intern is ending their turn 13 with 26  and 5 cards in HQ.
2woke2smoke started their turn 13 with 1  and 2 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  and 1  to install Gang Sign.
2woke2smoke is ending their turn 13 with 0  and 4 cards in their Grip.
Capslock Intern started their turn 14 with 26  and 5 cards in HQ.
Capslock Intern spends  to purge all virus counters.
Capslock Intern discards a card from their HQ.
Capslock Intern is ending their turn 14 with 26  and 5 cards in HQ.
2woke2smoke started their turn 14 with 0  and 4 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to gain 1 .
2woke2smoke discards The Turning Wheel from their Grip.
2woke2smoke discards Aumakua from their Grip.
2woke2smoke is ending their turn 14 with 1  and 5 cards in their Grip.
Capslock Intern started their turn 15 with 26  and 5 cards in HQ.
Capslock Intern spends  to install a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  to install a card in Server 3.
Capslock Intern is ending their turn 15 with 25  and 4 cards in HQ.
2woke2smoke started their turn 15 with 1  and 5 cards in their Grip.
2woke2smoke spends  to draw a card.
2woke2smoke spends  to draw a card.
2woke2smoke trashes Sneakdoor Beta from their Rig.
2woke2smoke spends  and 1  to install Cache.
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke uses Cache to gain 1 .
2woke2smoke spends  to use The Supplier to host GPI Net Tap.
2woke2smoke is ending their turn 15 with 3  and 5 cards in their Grip.
Capslock Intern spends 1  to rez Museum of History.
Capslock Intern uses Museum of History to shuffle Museum of History into R&D.
Capslock Intern started their turn 16 with 24  and 4 cards in HQ.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern spends  and 1 to advance a card in Server 1.
Capslock Intern scores Corporate Sales Team and gains 2 agenda points.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Special Report from HQ.
2woke2smoke accesses Hedge Fund from HQ.
2woke2smoke uses Gang Sign to access 1 card from HQ.
2woke2smoke accesses Special Report from HQ.
2woke2smoke accesses Project Vitruvius from HQ.
2woke2smoke steals Project Vitruvius and gains 2 agenda points.
2woke2smoke uses Leela Patel: Trained Pragmatist to add ICE protecting Server 3 at position 0 to HQ.

Capslock Intern
hold on

2woke2smoke
ok

Capslock Intern
You accessed 2 cards for each gang sign

2woke2smoke
crap

2woke2smoke
well

Capslock Intern
how did that happen

2woke2smoke
glitch

2woke2smoke
hm

2woke2smoke
ok

2woke2smoke
well

2woke2smoke
i'll concede then

2woke2smoke
cheers

2woke2smoke
gg

Capslock Intern
sorry man
2woke2smoke concedes.
Capslock Intern wins the game.
2woke2smoke left the game.

image

### LINKED ISSUE #2958: Dadiana Chacon not trashed when played at 2c with Scarcity of Resources in play
EricF spends 2  and  to install Dadiana Chacon.
EricF spends  to make a run on HQ.
EricF places a power counter on The Turning Wheel.
EricF jacks out.
EricF discards GS Striker M1 from their Grip.
EricF is ending their turn 5 with 0 and 5 cards in their Grip.

### LINKED ISSUE #2960: EMP Device blocking ICE rez several turns later after used with Counter Surveillance
Counter Surveillance run was on R&D when EMP was fired.  Later run on a remote.

### LINKED ISSUE #2963: Skorpios prevents Maker's Eye from working

### PR DESCRIPTION
**Pull request by danhut**
screen shot 2017-11-10 at 7 36 58 pm

fix #2946 
fix #2949 
fix #2904 
fix #2925 
fix #2956
fix #2910 
fix #2938 
fix #2957 
fix #2958
fix #2934 
fix #2894 
fix #2412
fix #2960 
fix #2963

### CODE REVIEW

File: src/cljs/netrunner/gameboard.cljs [hunk 1]
```diff
@@ -1183,7 +1183,9 @@
                       [:button {:on-click #(send-command "choice" {:choice c})}
                        (for [item (get-message-parts c)] (create-span item))]
                       (let [[title code] (extract-card-info (add-image-codes (:title c)))]
-                        [:button {:on-click #(send-command "choice" {:card @c}) :id code} title]))))))]
+                        (if (:rotated c)
+                          [:button.rotated {:on-click #(send-command "choice" {:card @c}) :id code} title]
+                          [:button {:on-click #(send-command "choice" {:card @c}) :id code} title])))))))]
```
Comment (Saintis) [inline src/cljs/netrunner/gameboard.cljs]: You could probably rewrite this to use `{:class (when (:rotated c) :rotated) ...}` instead of the `if` statement, which might look cleaner.

File: src/clj/game/cards/hardware.clj [hunk 2]
```diff
@@ -2,7 +2,7 @@
 
 (def cards-hardware
   {"Adjusted Matrix"
-   {:implementation "Click Adjusted Matrix to use ability"
+   {:implementation "Click Adjusted Matrix to use ability. Strength of breaker not validated."
```
Comment (Saintis) [inline src/clj/game/cards/hardware.clj]: This is true, although I don't think we validate the strength of any breakers.

File: src/cljs/netrunner/gameboard.cljs (hunk 1 above)
Comment (danhut) [reply src/cljs/netrunner/gameboard.cljs]: This is nicer.  I hate FAQ time.

**Comment by danhut** [comment]
What remains to be done:
1. Handle Doppelganger + Mobius. Both Doppelgänger and Möbius meet their trigger conditions at the same time, so the Runner chooses the order that the abilities trigger.
2. Check if Obelus is a problem. The Runner draws 1 card for each card accessed during the run, 
even if those cards are accessed from a server other than the attacked server.  Hades Shard + Obelus combo is: run HQ / R&D > pop Hades Shard > access all X cards in Archives > Access Y cards in HQ / R&D > Draw X + Y cards

Sad face.

**Comment by danhut** [comment]
The fix is on MR Stone specifically. If it involves him is should work. What’s the issue with DRT?

**Comment by ch1102chiou** [comment]
When I duplicate the this issue. I found Cleaner doesn't trigger when DRT
trigger.
Add snapshot.

[image: Inline image 1]

**Comment by danhut** [comment]
Thx. Will be same fix

File: src/clj/game/core/runs.clj [hunk 3]
```diff
@@ -697,7 +697,7 @@
     (:successful run)
     (do
       (play-sfx state side "run-successful")
-      (trigger-event-sync state side eid :successful-run-ends run))
+      (trigger-event-simult state side eid :successful-run-ends nil run))
```
Comment (nealterrell) [inline src/clj/game/core/runs.clj]: Why this change?

Comment (danhut) [reply src/clj/game/core/runs.clj]: It was a part solution to handling the interaction between Doppelganger + Data Breach/Mobius.  I have been thinking about that today and think those cards just need a re-write such they use the same EID for their prompt and the run they actually fire.

Comment (nealterrell) [reply src/clj/game/core/runs.clj]: Gotcha 👍

Comment (danhut) [reply src/clj/game/core/runs.clj]: Figured it out - booyah!

**Comment by danhut** [comment]
Final change for faq4.1 I hope - the dreaded Doppelganger/Mobius/Data Breach

**Comment by danhut** [comment]
@Eric-Fletcher thanks - good call.  Using Skorp on a run-event before it has resolved also breaks the run-event.  I will need to go a bit deeper into the engine to resolve the issue then rather than do it from Skorp itself.

File: src/clj/game/cards/resources.clj [hunk 4]
```diff
@@ -1316,6 +1316,7 @@
              {:effect (effect (update! (assoc card :slums-active true)))}
              :pre-trash
              {:req (req (and (:slums-active card)
+                             (not (= (:title target) "Mumbad Virtual Tour"))
```
Comment (nealterrell) [inline src/clj/game/cards/resources.clj]: I'd prefer an implementation that doesn't couple this card to the specific name of another card. Let's go with a `:flag` in MVT and then Slums can check the target's card-def for that flag.

File: src/clj/game/cards/ice.clj [hunk 5]
```diff
@@ -1664,13 +1664,13 @@
     :implementation "Does not handle UFAQ for Pawn or Blackguard interaction"
     :cannot-host true
     :subroutines [trash-program
+                  end-the-run
                   {:label "Trash a resource and end the run"
```
Comment (nealterrell) [inline src/clj/game/cards/ice.clj]: Fix this label :).

File: src/clj/game/cards/assets.clj [hunk 6]
```diff
@@ -1483,6 +1483,16 @@
    "Turtlebacks"
    {:events {:server-created {:msg "gain 1 [Credits]" :effect (effect (gain :credit 1))}}}
 
+   "Urban Renewal"
+   {:effect (effect (add-counter card :power 3))
+    :derezzed-events {:runner-turn-ends corp-rez-toast}
+    :events {:corp-turn-begins
```
Comment (nealterrell) [inline src/clj/game/cards/assets.clj]: The `:corp-turn-begins` effect should be `:delayed-completion`.

File: src/clj/game/cards/assets.clj [hunk 7]
```diff
@@ -1483,6 +1483,16 @@
...
+             {:effect (req (add-counter state side card :power -1)
+                           (when (<= (get-in card [:counter :power]) 1)
+                             (system-msg state :corp "uses Urban Renewal to do 4 meat damage")
+                             (trash state side card {:cause :ability-cost})
```
Comment (nealterrell) [inline src/clj/game/cards/assets.clj]: For future-proofing, you should await this function with `when-completed`, and then call `damage`.

File: src/clj/game/cards/assets.clj [hunk 8]
```diff
@@ -1483,6 +1483,16 @@
    "Turtlebacks"
    {:events {:server-created {:msg "gain 1 [Credits]" :effect (effect (gain :credit 1))}}}
 
+   "Urban Renewal"
+   {:effect (effect (add-counter card :power 3))
+    :derezzed-events {:runner-turn-ends corp-rez-toast}
+    :events {:corp-turn-begins
+             {:effect (req (add-counter state side card :power -1)
+                           (when (<= (get-in card [:counter :power]) 1)
```
Comment (nealterrell) [inline src/clj/game/cards/assets.clj]: Since this ability needs to be `:delayed-completion`, you'll need to trigger `effect-completed` if this condition is false.

File: src/clj/game/cards/hardware.clj [hunk 9]
```diff
@@ -4,9 +4,20 @@
   {"Acacia"
    {:events {:pre-purge {:effect (req (let [virus (filter #(has-subtype? % "Virus") (all-installed state :runner))
                                             counters (reduce + (map #(get-virus-counters state :runner %) virus))]
```
Comment (nealterrell) [inline src/clj/game/cards/hardware.clj]: We may need a UFAQ ruling on this interaction with Hivemind down the road. We can leave it for now.

**Comment by nealterrell** [comment]
This is looking good, @danhut . I added 2-3 comments and then we're good to go.

**Comment by danhut** [comment]
@nealterrell Should be sorted -thanks for the review.

**Comment by nealterrell** [comment]
LET'S DO THIS 🥇
