### PR TITLE
fix Élivágar Bifurcation score effect

### LINKED ISSUE #6443: Élivágar Bifurcation Prompt doesnt close
The prompt for scoring Bifurcation doesnt close when clicking done. The derez ability is a may so I expected this to be the way to "refuse" the trigger. Clicking "done" multiple times didnt remove the window for me either. It has happened every time I score the agenda. This issue has occured to me while playing sportsmetal which also triggers on score so the issue might be related to multiple triggers on score happening.

There is a workaround by just using the /close-prompt command. Hasnt caused any further issues for me after using it.

To replicate the issue you start the game with sportsmetal and just score the agenda normally (install adv adv).

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6443

### CODE REVIEW

File: src/clj/game/cards/agendas.clj [hunk 1]
```diff
@@ -670,10 +670,12 @@
 (defcard "Élivágar Bifurcation"
   {:on-score
    {:interactive (req true)
+    :async true
```
Comment (NoahTheDuke) [inline src/clj/game/cards/agendas.clj:673]: Gotta leave this out.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
