### PR TITLE
fix mark triggering multiple times

### LINKED ISSUE #6425: Virtuoso and Sable triggers the mark selection twice.
ChrisFerg started their turn 12 with 12  and 5 cards in their Grip.
ChrisFerg identifies their mark to be R&D.
ChrisFerg identifies their mark to be R&D.

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6425 and should address #6431 🤞

### CODE REVIEW

File: src/clj/game/core/mark.clj [hunk 1]
```diff
@@ -19,5 +20,5 @@
     (system-msg state :runner (str "identifies their mark to be " (central->name new-mark)))))
 
 (def identify-mark-ability
-  {:req (req (nil? (:mark @state)))
```
Comment (NoahTheDuke) [inline src/clj/game/core/mark.clj:22]: I'm only okay with this if the CR says that "Identify Your Mark" always happens but game state changes only if there's no existing mark.

Comment (NBKelly) [reply src/clj/game/core/mark.clj:22]: I think that's what the text says for mark.
> When your turn begins, identify your mark. (If you don’t have a mark, a random central server becomes your mark for this turn.)

So identify should always happen, but the gamestate only changes the first time each turn.

Comment (NoahTheDuke) [reply src/clj/game/core/mark.clj:22]: Ah yeah, god point. I forgot that's how they worded the reminder text. Cool!
