### PR TITLE
Miss Bones Fix for trashing on empty

### LINKED ISSUE #4303: MIss Bones does not trash when empty
Nuff said

### PR DESCRIPTION
**Pull request by NoahTheDuke**
This is the start of a larger refactor, as other cards should operate under this functionality as well.

Closes #4303

### CODE REVIEW

File: src/clj/game/cards/assets.clj [hunk 1]
```diff
@@ -38,16 +38,15 @@
...
   [counters per-turn]
   (let [ability {:msg (str "gain " per-turn " [Credits]")
-                 :counter-cost [:credit per-turn]
                  :once :per-turn
                  :req (req (:corp-phase-12 @state))
                  :label (str "Gain " per-turn " [Credits] (start of turn)")
-                 :effect (req (gain-credits state :corp per-turn)
-                              (when (zero? (get-counters card :credit))
-                                (trash state :corp card)))}]
+                 :effect (effect (gain-credits (min per-turn (get-counters card :credit)))
```
Comment (lostgeek) [inline src/clj/game/cards/assets.clj]: Future-proofing. I love it :+1:

File: src/clj/game/cards/assets.clj [hunk 2]
```diff
@@ -585,7 +584,6 @@
    "Drudge Work"
    {:effect (effect (add-counter card :power 3))
     :abilities [{:cost [:click 1]
-                 :counter-cost [:power 1]
```
Comment (lostgeek) [inline src/clj/game/cards/assets.clj]: I think, this can stay. Imho, the ruling would be that Drudge Work is already in the Archives, when it is doing the reshuffling of the last agenda..

You first pay the costs of the paid ability. Then there is a checkpoint, in which Drudge Work gets trashed because there are no power counters left. And then you're doing the ability, which exists even if the card got trashed.

Maybe we should ask the rules team on this.

File: src/clj/game/cards/assets.clj [hunk 3]
```diff
@@ -1477,11 +1475,11 @@
    "Private Contracts"
    {:effect (effect (add-counter card :credit 14))
     :abilities [{:cost [:click 1]
-                 :counter-cost [:credit 2]
```
Comment (lostgeek) [inline src/clj/game/cards/assets.clj]: (re: the comment on Drudge Work) This one should be ok.

File: src/clj/game/cards/hardware.clj [hunk 4]
```diff
@@ -1048,11 +1048,10 @@
    {:data [:counter {:power 4}]
     :interactions {:prevent [{:type #{:meat}
                               :req (req true)}]}
-    :abilities [{:counter-cost [:power 1]
```
Comment (lostgeek) [inline src/clj/game/cards/hardware.clj]: See Drudge Work.

File: src/clj/game/cards/resources.clj [hunk 5]
```diff
@@ -614,7 +606,13 @@
       :abilities [ability]
       :move-zone heap-event
       :events {:runner-turn-begins ability
-               :runner-turn-ends nil}})
+               :runner-turn-ends nil
+               :counter-added {:req (req (not (pos? (get-counters card :credit))))
```
Comment (lostgeek) [inline src/clj/game/cards/resources.clj]: Doesn't this need a `(req (same-card? card target)`?

File: src/clj/game/cards/resources.clj [hunk 6]
```diff
@@ -1186,10 +1184,8 @@
     :interactions {:prevent [{:type #{:meat}
                               :req (req true)}]}
     :abilities [{:label "Prevent 1 meat damage"
-                 :counter-cost [:power 1]
```
Comment (lostgeek) [inline src/clj/game/cards/resources.clj]: See Drudge Work.

File: src/clj/game/cards/resources.clj [hunk 7]
```diff
@@ -1308,11 +1304,10 @@
    "Liberated Account"
    {:data {:counter {:credit 16}}
     :abilities [{:cost [:click 1]
-                 :counter-cost [:credit 4]
```
Comment (lostgeek) [inline src/clj/game/cards/resources.clj]: This is fine.

File: src/clj/game/core/cards.clj [hunk 8]
```diff
@@ -227,7 +227,7 @@
            (if-not placed
              (trigger-event state side :advance (get-card state updated-card))
              (trigger-event state side :advancement-placed (get-card state updated-card))))
-       (trigger-event state side :counter-added (get-card state updated-card))))))
+       (trigger-event-sync state side (make-eid state) :counter-added (get-card state updated-card))))))
```
Comment (lostgeek) [inline src/clj/game/core/cards.clj]: Maybe as future-proofing add `(make-eid state {:source card :source-type :add-prop})`

File: src/clj/game/cards/resources.clj [hunk 9]
```diff
@@ -1391,13 +1391,11 @@
     :interactions {:pay-credits {:req (req (and (= :runner-trash-corp-cards (:source-type eid))
                                                 (installed? target)))
                                  :type :credit}}
-    :abilities [{:counter-cost [:credit 1]
```
[the remark this answers is not in the document]
Comment (NoahTheDuke) [reply src/clj/game/cards/resources.clj]: Yeah, I might have been too excited here. Fully switching over should probably happen another time.

File: src/clj/game/cards/assets.clj (hunk 1 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/assets.clj]: Yeah, I’ve heard whispers of an Uprising card that places credits on cards, and technically these abilities aren’t costs, they’re effects, so you always do as much as possible.

File: src/clj/game/cards/assets.clj (hunk 2 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/assets.clj]: No, you’re totally right! I got over-zealous and forgot what the heck I was doing haha. This is the perfect place for `:counter-cost`.

File: src/clj/game/cards/resources.clj (hunk 5 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/resources.clj]: Yep! Good catch.

File: src/clj/game/core/cards.clj (hunk 8 above)
Comment (NoahTheDuke) [reply src/clj/game/core/cards.clj]: Smart.
