### PR TITLE
FIX: Aumakua shouldn't gain counters from using trash abilities

### LINKED ISSUE #3479: Aumuka gains virus counters when trashing with Freedom's ID ability
Yeah that's about it.

### PR DESCRIPTION
**Pull request by NoahTheDuke**
The trash ability wasn't setting `@state [:run :did-trash]`, so Aumakua triggered on it's usage. This corrects that miss.

Fixes #3479, #3347

### CODE REVIEW

File: test/clj/game_test/cards/identities.clj [hunk 1]
```diff
@@ -481,6 +481,20 @@
...
+      (is (not (:run @state)) "Run ended")))
+  (testing "Shouldn't give Aumakua additional counters on trash. #3479"
+    (do-game
+      (new-game (default-corp [(qty "Ice Wall" 10)])
+                (make-deck "Freedom Khumalo: Crypto-Anarchist" ["Cache" "Aumakua"]))
+      (take-credits state :corp)
+      (play-from-hand state :runner "Cache")
+      (play-from-hand state :runner "Aumakua")
+      (run-empty-server state "R&D")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Shouldn't have any virus counters yet.")
```
Comment (Saintis) [inline test/clj/game_test/cards/identities.clj]: What should not have virus counters?

File: test/clj/game_test/cards/identities.clj [hunk 2]
```diff
@@ -481,6 +481,20 @@
...
+      (prompt-choice-partial :runner "Freedom")
+      (prompt-select :runner (get-program state 0))
+      (is (= 1 (count (:discard (get-corp)))) "Card should be discarded now")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Doesn't gain any virus counters from trash ability.")
```
Comment (Saintis) [inline test/clj/game_test/cards/identities.clj]: What doesn't gain?

File: test/clj/game_test/cards/identities.clj [hunk 3]
```diff
@@ -481,6 +481,20 @@
...
+      (new-game (default-corp [(qty "Ice Wall" 10)])
+                (make-deck "Freedom Khumalo: Crypto-Anarchist" ["Cache" "Aumakua"]))
+      (take-credits state :corp)
+      (play-from-hand state :runner "Cache")
+      (play-from-hand state :runner "Aumakua")
+      (run-empty-server state "R&D")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Shouldn't have any virus counters yet.")
+      (prompt-choice-partial :runner "Freedom")
+      (prompt-select :runner (get-program state 0))
+      (is (= 1 (count (:discard (get-corp)))) "Card should be discarded now")
```
Comment (Saintis) [inline test/clj/game_test/cards/identities.clj]: What card? Accessed card?

File: test/clj/game_test/cards/identities.clj [hunk 4]
```diff
@@ -490,11 +490,11 @@
...
       (play-from-hand state :runner "Aumakua")
       (run-empty-server state "R&D")
-      (is (nil? (->> (get-program state 1) :counter :virus)) "Shouldn't have any virus counters yet.")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Aumakuma shouldn't have any virus counters yet.")
       (prompt-choice-partial :runner "Freedom")
       (prompt-select :runner (get-program state 0))
-      (is (= 1 (count (:discard (get-corp)))) "Card should be discarded now")
-      (is (nil? (->> (get-program state 1) :counter :virus)) "Doesn't gain any virus counters from trash ability.")
+      (is (= 1 (count (:discard (get-corp)))) "Ice Wall should be discarded now")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Aumakuma oesn't gain any virus counters from trash ability.")
```
Comment (Saintis) [inline test/clj/game_test/cards/identities.clj]: Typo! 😛

Comment (NoahTheDuke) [reply test/clj/game_test/cards/identities.clj]: Damn!

File: test/clj/game_test/cards/identities.clj [hunk 5]
```diff
@@ -494,7 +494,7 @@
       (prompt-choice-partial :runner "Freedom")
       (prompt-select :runner (get-program state 0))
       (is (= 1 (count (:discard (get-corp)))) "Ice Wall should be discarded now")
-      (is (nil? (->> (get-program state 1) :counter :virus)) "Aumakuma oesn't gain any virus counters from trash ability.")
+      (is (nil? (->> (get-program state 1) :counter :virus)) "Aumakua oesn't gain any virus counters from trash ability.")
```
Comment (jwarwick) [inline test/clj/game_test/cards/identities.clj]: `oesn't` -> `doesn't`

Comment (NoahTheDuke) [reply test/clj/game_test/cards/identities.clj]: Heck!!!!!!
