### PR TITLE
Make run abilities persist after trash

### LINKED ISSUE #5754: Stargate does not trigger when trashed during a run
When Stargate is used to make a run and is then trashed during that run, it fails to trigger when the run is successful (instead I get an ordinary R&D access). I believe this behaviour is incorrect.

### LINKED ISSUE #6049: Stargate trashed by Balista mid-run
Link to bug replay: https://jinteki.net/bug-report/6a2d86ea-c963-4df0-b3be-1bba4192b765?b=0

Description:

I used Stargate to run R&D, which was protected by Ballista. Corp trashed Stargate then I breached, but I accessed cards like normal instead of draw 3/trash 1. Somebody in Discord said this wasn't working correctly.
This was a demo game where I was controlling both sides.

### PR DESCRIPTION
**Pull request by cardboardtech**
Updated Stargate, Keyhole, Analog Dreamers, and Expert Schedule Analyzer to have their effects persist even if they are trashed during the course of the run. Modeled the fix off of how we implemented Counter Surveillance.

fix #5754
fix #6049

### CODE REVIEW

File: src/clj/game/cards/programs.clj [hunk 1]
```diff
@@ -1139,19 +1139,19 @@
...
+                  :ability
+                  {:msg (msg "reveal all of the cards cards in HQ: "
+                             (string/join ", " (map :title (:hand corp))))
+                   :async true
+                   :effect (effect (reveal eid (:hand corp)))}})]
+    {:abilities [{:cost [:click 1]
+                  :msg "make a run on HQ"
+                  :makes-run true
+                  :async true
+                  :effect (effect (register-events card [(assoc ability :duration :end-of-run)])
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:1153]: You can just put the duration directly on the ability. (Same with the other card abilities in this PR.) the ability maps aren't used elsewhere so you don't have to worry about the duration leaking into another usage.

**Review by NoahTheDuke — APPROVED** [review]
