### PR TITLE
Fix hosting of free-mu-based breakers

### LINKED ISSUE #2535: Hosting Adept on Dhegdheer after installing does not properly boost strength
Installing Adept on Dhegdheer after the former is already installed (e.g. through SMC) your MU will update properly but Adept will still count it's own MU and won't have increased strength. This can be fixed by moving Adept back to hand and reinstalling it directly with Dhegdheer.

### PR DESCRIPTION
**Pull request by jwarwick**
Better support for `Adept` and `Savant` when hosted on `Dhegdheer`, `Leprechaun`, and `Dinosaurus`. 

Previously the strength of the breakers was not increased by the amount of MU freed up when they were hosted.

Fixes #2535

### CODE REVIEW

File: src/clj/game/cards/hardware.clj [hunk 1]
```diff
@@ -296,9 +296,13 @@
                                       (not (has-subtype? % "AI"))
                                       (installed? %))}
                  :msg (msg "host " (:title target))
-                 :effect (req (update-breaker-strength state side (host state side card target))
-                              (update! state side (assoc (get-card state card) :dino-breaker (:cid target)))
-                              (gain state side :memory (:memoryunits target)))}]
+                 :effect (req (gain state side :memory (:memoryunits target))
+                              (update-breaker-strength state side target)
```
Comment (nealterrell) [inline src/clj/game/cards/hardware.clj]: Is this line necessary given what happens in the `->>` next?

File: src/clj/game/cards/hardware.clj [hunk 2]
```diff
@@ -296,9 +296,13 @@
...
+                              (->> target
+                                (get-card state)
+                                (host state side card)
+                                (update-breaker-strength state side))
+                              (update! state side (assoc (get-card state card) :dino-breaker (:cid target))))}]
```
Comment (nealterrell) [inline src/clj/game/cards/hardware.clj]: Can we put this key in `:special`?

File: src/clj/game/cards/programs.clj [hunk 3]
```diff
@@ -236,19 +236,21 @@
...
-                                 (when (-> target :cost pos?)
-                                   (gain state side :credit 1))
-                                 (gain :memory (:memoryunits target))
-                                 (update! (assoc (get-card state card) :dheg-prog (:cid target))))}
+                 :effect (req (gain state side :memory (:memoryunits target))
+                              (when (-> target :cost pos?)
+                                (gain state side :credit 1))
+                              (update-breaker-strength state side target)
+                              (host state side card (get-card state target))
+                              (update! state side (assoc (get-card state card) :dheg-prog (:cid target))))}
```
Comment (nealterrell) [inline src/clj/game/cards/programs.clj]: Likewise re: `:special`

File: src/clj/game/cards/programs.clj [hunk 4]
```diff
@@ -236,19 +236,21 @@
                  :choices {:req #(and (is-type? % "Program")
                                       (installed? %))}
                  :msg (msg "host " (:title target) (when (-> target :cost pos?) ", lowering its cost by 1 [Credit]"))
-                 :effect (effect (host card target)
-                                 (when (-> target :cost pos?)
-                                   (gain state side :credit 1))
-                                 (gain :memory (:memoryunits target))
-                                 (update! (assoc (get-card state card) :dheg-prog (:cid target))))}
+                 :effect (req (gain state side :memory (:memoryunits target))
+                              (when (-> target :cost pos?)
```
[the remark this answers is not in the document]
Comment (jwarwick) [reply src/clj/game/cards/programs.clj]: The trick is that I keep needing to get an updated card state. Not crazy about how this is done, but didn't find the inspiration to greatly change it. Otherwise it would just end up in a `let`.

[the remark this answers is not in the document]
Comment (jwarwick) [reply src/clj/game/cards/programs.clj]: Sorry, you meant the single line thread. I'm ambivalent on that one. I thought you meant my terrible nested update function.
