### PR TITLE
Fix Kasi String not adding itself to score area when charged up to 4

### LINKED ISSUE #6498: Kasi String does not add to score area after a Daeg trigger puts 4 counters on it.
Kasi String on 2 counters, run R&D, Padma adds a counter to go to 3 on Kasi, access Project Atlas off R&D to steal, Daeg adds a counter to Kasi to go to 4 counters, but Kasi did not go to score area. Running a remote to go to 5 effective counters did trigger add to score area.. So maybe the timing on checking Kasi needs a look?

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6498.

Also improved some other tests.

### CODE REVIEW

File: src/clj/game/cards/resources.clj [hunk 1]
```diff
@@ -1590,20 +1590,23 @@
...
+             :optional
+             {:req (req (and (first-event? state :runner :run-ends #(is-remote? (:server (first %))))
+                             (not (:did-steal target))
+                             (:did-access target)
+                             (is-remote? (:server target))))
+              :autoresolve (get-autoresolve :auto-kasistring)
+              :waiting-prompt "Runner to choose an option"
+              :prompt "Place 1 power counter on Kasi String?"
+              :yes-ability {:msg "place a power counter on itself"
+                            :effect (req (add-counter state side eid card :power 1 {:placed true}))}
```
Comment (NoahTheDuke) [inline src/clj/game/cards/resources.clj:1603]: Needs `:async true`.
