### PR TITLE
Don't process abilities while a prompt is open

### LINKED ISSUE #5705: Feature idea: Do not allow cards to resolve abilities while a prompt of that card is open
There often are situations, where players open a second prompt, while still resolving the first on the same card (e.g. trying to break a subroutine, while already being in the prompt for breaking subroutines with the same card). We could disable resolving card abilities on cards, while a prompt of that card is still open.

### LINKED ISSUE #5776: Suggestion:  Stopping the Game while the Corp is acting
Not actually sure if this is a suggestion per se, but for some cards in the game, the Runner gets no indication that the Corp is doing something (this may be the case for some Runner cards as well but I'm not sure).  For example, while the Corp is making a decision with Climactic Showdown, the runner can keep doing things.  My intuition is that the game should pause while the Corp chooses, then allow the players to proceed, since this is a required effect.

Similarly, I have noticed that using Spin Doctor doesn't alert the Runner that the Corp is deciding on cards.  For example, firing Spin Doctor after discarding allows the runner to carry on their turn while the Corp chooses.

Not huge deals, but just wondering if it could be implemented that when the Corp is making a decision on these cards, the Runner is required to wait.  Thanks!

### LINKED ISSUE #6923: [BUG] Broke interface
Link to bug replay: https://jinteki.net/bug-report/8f219553-006d-4239-a97f-b4f95b364b3c?b=0

Description:

Somehow broke the interface. Only "strange move" / unexpected actions is boosting black orchestra during access using trickster taka around turn 8 (not remembering the exact turn)

### LINKED ISSUE #6930: [BUG] (Minor) Internal server error with unexpected actions from the player
Link to bug replay: https://jinteki.net/bug-report/b78b3df8-4a29-414f-955e-55b28914bb5b?b=0

Description:
Doing Paperclip install from Overclock while the Corp is doing Ob install from firing border control

### LINKED ISSUE #7198: "bblum uses Stegodon MK IV to shuffle Spin Doctor and 1 unseen card into R&D."
Link to bug replay: https://jinteki.net/bug-report/549a9087-06ef-47b5-945a-698fee7a1adf?b=0

Description:

I believe this is similar to other multiple-overlapping-prompt issues, like #6727 and #6718, but this time it manifested in the game log in this amusing and also surprisingly self-explanatory way, so I thought I'd share.

Additional detail: After resolving the first shuffle-2 ability, I got another prompt to shuffle 2 with spin dr, and _no_ stegodon prompt (which I just resolved manually) -- as if spin's ability had been copied onto the stegodon prompt.

### PR DESCRIPTION
**Pull request by NBKelly**
Also tags prevention prompts so we can check against them being open.

Prevents players from using card abilities, firing subroutines, expending, or playing dynamic abilities while a prompt is open (another ability is resolving). Actions already block, so there wasn't a need to touch those.

I fixed the unit tests that deliberately played the game wrong, since it's no longer possible to do that.

Closes #5705
Closes #6930 (no longer possible)
Closes #6923 (prevents the scenario where it would happen)
Closes #7198 (prevents overlapping prompts)
Closes #5776 (prevents acting while a prompt is open)

### CODE REVIEW

File: src/clj/game/core/actions.clj [hunk 1]
```diff
@@ -37,6 +37,19 @@
...
       (swap! state assoc :click-states click-states))))
 
+(defn- valid-prompt-state?
+  [state side]
+  (let [prompt-type (get-in @state [side :prompt-state :prompt-type])]
+    (or (= nil prompt-type)
+        (= :run prompt-type)
+        (= :prevent prompt-type))))
+
+(defn- no-prompt?
```
Comment (NoahTheDuke) [inline src/clj/game/core/actions.clj:47]: This implementation does not check  that there's no prompt, so the name should change or the impl should change.

File: src/clj/game/core/actions.clj [hunk 2]
```diff
@@ -73,7 +88,8 @@
   (let [card (get-card state card)
         eid (make-eid state {:source card :source-type :ability})
         expend-ab (expend (:expend card))]
-    (resolve-ability state side eid expend-ab card nil)))
+    (when (no-prompt? state side)
```
Comment (NoahTheDuke) [inline src/clj/game/core/actions.clj:91]: Move this before the let.
