### PR TITLE
Fix Leave No Trace derezzing pre-rezzed modified ICE

### LINKED ISSUE #3121: Leave No Trace derezzes ICE advanced via Reconstruction Contract
This one is a bit weird to reproduce.

I had a rezzed Firewall on HQ and my opponent used Leave No Trace to make a run on a remote server.  I trashed a Reconstruction Contract with some counters on it and advanced the Firewall.  Once the run ended, the Firewall derezzed due to Leave No Trace.  I'm guessing it's not specifically Reconstruction Contract, might be easier to reproduce with Matrix Analyzer or Space Camp.

### PR DESCRIPTION
**Pull request by butzopower**
Fixes #3121 

Compare previously rezzed ICE with post-run rezzed ICE via their :cids instead of the cards themselves.

There's probably still some edge cases for LNT if the runner derezzes midrun with a bird breaker and the corp loops them back somehow and rezzes, but that seems like a pretty crazy edge case and would have been the case with the old implementation as well.

### CODE REVIEW

File: src/clj/game/cards/events.clj [hunk 1]
```diff
@@ -948,24 +948,27 @@
...
-                                           old (set (:lnt @state))
-                                           diff (seq (clojure.set/difference new old))]
-                                       (doseq [ice diff]
-                                         (derez state side ice))
-                                       (when-not (empty? diff)
-                                         (system-msg state side (str "derezzes " (join ", " (map :title diff)) " via Leave No Trace")))
-                                       (swap! state dissoc :lnt)
-                                       (unregister-events state side card)))}}}
+   (letfn [(get-rezzed-cids [ice]
+             (map #(:cid %) (filter #(and (rezzed? %) (is-type? % "ICE")) ice)))]
```
Comment (nealterrell) [inline src/clj/game/cards/events.clj]: If you ever find yourself writing `#(_some_function %)`, just use `_some_function` instead, as in `(map :cid ...)`.

Comment (butzopower) [reply src/clj/game/cards/events.clj]: Ah, makes sense, always forget that `:xxx` is a function.  Should be fixed now.
