### PR TITLE
fix for Exile interaction with Harbinger

### LINKED ISSUE #4598: Trashing Harbinger triggers Exile: Streethawk id ability
When Harbinger is trashed and installs itself facedown, it incorrectly triggers the draw from Exile: Streethawk.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4598 

It seems that Harbinger enters discard briefly, before its ability triggers and reinstalls itself facedown. Proper fix would be to prevent Harbinger ever entering discard, right? Is there any way to do that?

Current fix prevents Exile's ability to trigger, if program is being installed facedown.

### CODE REVIEW

File: test/clj/game_test/cards/identities.clj [hunk 1]
```diff
@@ -772,7 +772,23 @@
...
+      (take-credits state :corp)              
+      (starting-hand state :runner ["Harbinger"])      
+      (play-from-hand state :runner "Harbinger")
+      (let [harb (get-program state 0)
+            grim (get-ice state :hq 0)]
+        (run-on state :hq)
+        (core/rez state :corp grim)
+        (card-subroutine state :corp (refresh grim) 0)
+        (click-card state :corp harb)
+        (is (= 0 (count (:hand (get-runner)))) "Exile didn't drew a card")))))
```
Comment (lostgeek) [inline test/clj/game_test/cards/identities.clj]:
```suggestion
        (is (= 0 (count (:hand (get-runner)))) "Exile didn't draw a card")))))
```
typo

File: test/clj/game_test/cards/identities.clj [hunk 2]
```diff
@@ -772,7 +772,23 @@
       ;; Make sure the simultaneous-resolution prompt is showing with 2 choices
       (is (= 2 (-> (get-runner) :prompt first :choices count)) "Simultaneous-resolution prompt is showing")
       (click-prompt state :runner "Exile: Streethawk")
-      (is (= 1 (count (:hand (get-runner)))) "Exile drew a card"))))
+      (is (= 1 (count (:hand (get-runner)))) "Exile drew a card")))
+  (testing "Interaction with harbringer"
```
Comment (lostgeek) [inline test/clj/game_test/cards/identities.clj]:
```suggestion
  (testing "Interaction with harbinger"
```
The card is called Harbinger :slightly_smiling_face:

File: test/clj/game_test/cards/identities.clj [hunk 3]
```diff
@@ -772,7 +772,23 @@
...
+    (do-game
+      (new-game {:corp {:deck ["Grim"]}
+                 :runner {:id "Exile: Streethawk"
+                          :deck ["Harbinger", (qty "Sure Gamble" 10)]}})
```
Comment (lostgeek) [inline test/clj/game_test/cards/identities.clj]:
```suggestion
                          :deck ["Harbinger" (qty "Sure Gamble" 10)]}})
```

**Comment by lostgeek** [comment]
I feel that Harbinger entering the discard for a moment is in line with the rules, but with the new Interrupt stuff this could be interpreted differently.

Exile not triggering on facedown installs is correct though no matter what, since facedown cards have no card type.

>8.4.2.Runner cards that are installed or turned facedown do not have a name, type, or subtypes, and their abilities are not active.
