### PR TITLE
Kate with bazaar fix

### LINKED ISSUE #4457: Kate / Bazaar
_Kate_'s discount applies to all copies installed via _Bazaar_ triggers.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4457 

Fixes Kate, Az, Reina and Watchdog abilities. New test cases for Bazaar.

### CODE REVIEW

File: src/clj/game/cards/assets.clj [hunk 1]
```diff
@@ -2250,18 +2250,15 @@
...
+   (letfn [(not-triggered? [state card] (no-event? state :runner :rez #(ice? (first %))))]
+     {:constant-effects [{:type :rez-cost
                           :req (req (and (ice? target)
                                          (not-triggered? state card)))
                           :value (req (- (count-tags state)))}]
       :events [{:event :rez
                 :req (req (and (ice? target)
                                (not-triggered? state card)))
-                :effect (req (mark-triggered state card))}]})
+                :msg (msg "reduce the install cost of " (:title target) " by " (count-tags state) " [Credits]")}]})
```
Comment (NoahTheDuke) [inline src/clj/game/cards/assets.clj]:
```suggestion
                :msg (msg "reduce the rez cost of " (:title target) " by " (count-tags state) " [Credits]")}]})
```

File: src/clj/game/cards/identities.clj [hunk 2]
```diff
@@ -1168,18 +1160,15 @@
...
+   (letfn [(not-triggered? [state card] (no-event? state :runner :rez #(ice? (first %))))]
+     {:constant-effects [{:type :rez-cost
                           :req (req (and (ice? target)
                                          (not-triggered? state card)))
                           :value 1}]
       :events [{:event :rez
                 :req (req (and (ice? target)
                                (not-triggered? state card)))
-                :effect (req (mark-triggered state card))}]})
+                :msg (msg "increased the install cost of " (:title target) " by 1 [Credits]")}]})
```
Comment (NoahTheDuke) [inline src/clj/game/cards/identities.clj]:
```suggestion
                :msg (msg "increased the rez cost of " (:title target) " by 1 [Credits]")}]})
```
