### PR TITLE
Slee vs Ankusa return to hand test

### LINKED ISSUE #5834: Chief Slee still getting counters when broken by Ankusa

### PR DESCRIPTION
**Pull request by NBKelly**
Essentially, we need to update the current encounter before we end it (by bouncing the card), because slee looks at what the current encounter was when the encounter ends.

Closes #5834

### CODE REVIEW

File: src/clj/game/cards/programs.clj [hunk 1]
```diff
@@ -493,8 +493,9 @@
                                              (all-subs-broken-by-card? (:ice context) card)))
                               :msg (msg "add " (:title (:ice context))
                                         " to HQ after breaking all its subroutines")
-                              :effect (effect (move :corp (:ice context) :hand nil)
-                                              (continue :runner nil))}]}))
+                              :effect (req (set-current-ice state (:ice context))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:496]: How is the context ice not already the current ice? That seems to be the real source of the bug.

Comment (NBKelly) [reply src/clj/game/cards/programs.clj]: Fair. I changed `runs.clj` to update the current ice after subs get broken, and it appears to have not broken anything.
