### PR TITLE
fix Meridian infinite approach when added to score area

### LINKED ISSUE #6819: Meridian subroutine causing infinite approach loop
Link to bug replay: https://jinteki.net/bug-report/a276cfac-7068-4fe3-80a7-63a8f44f20c2?b=0

Description:

**Circumstance**
Runner encounters Meridian as the only piece of ICE on a remote server.  The subroutine fires, the runner chooses to add Meridian to their score area as an agenda worth -1 point.

**Expected Behaviour**
The run continues, the runner breaches the server.

**Observed Behaviour**
The runner enters an infinite ICE approach loop

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6819

### CODE REVIEW

File: src/clj/game/cards/ice.clj [hunk 1]
```diff
@@ -2555,10 +2555,9 @@
                   :effect (req (if (str/starts-with? target "Corp")
                                  (wait-for (gain-credits state :corp 4)
                                            (end-run state :runner eid card))
-                                 (do (as-agenda state :runner card -1)
-                                     (if current-ice
-                                       (encounter-ends state side eid)
-                                       (effect-completed state side eid)))))}]})
+                                 (do (encounter-ends state side (make-eid state eid))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/ice.clj:2558]: Gotta be a wait-for.
