### PR TITLE
fix Info Bounty triggering on first breach

### LINKED ISSUE #6867: Info Bounty works on the second run on the mark if the first was unsuccessful or had the breach replaced.
Info Bounty should only trigger the first time a run on your mark ends not at the end of the run the first time you breached the server.

The thing I saw was someone pinholed through their mark which should eat the info Bounty trigger but when they went back they got the 2 credits.

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6867

### CODE REVIEW

File: src/clj/game/cards/resources.clj [hunk 1]
```diff
@@ -1540,13 +1540,16 @@
...
+            {:event :run-ends
               :async true
               :interactive (req true)
               :once :per-turn
-              :req (req (first-event? state side :end-breach-server #(is-mark? state (:from-server (first %)))))
-              :msg "gain 2 [Credits]"
-              :effect (effect (gain-credits eid 2))}]})
+              :req (req (first-event? state side :run-ends #(is-mark? state (target-server (first %)))))
+              :effect
+              (req (if (first-event? state side :end-breach-server #(is-mark? state (:from-server (first %))))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/resources.clj:1549]: This is genius.

**Review by NoahTheDuke — APPROVED** [review]
