### PR TITLE
Fix for additional-abilities on icebreakers

### LINKED ISSUE #4423: Tycoon no longer working automatically

### LINKED ISSUE #4429: Faerie nolonger trashes itself after used.
It happen twice in the same match from 2 different copies of Faerie

### PR DESCRIPTION
**Pull request by lostgeek**
The `:additional-ability` on a `break-sub` is now called multiple times during breaking.

Closes #4429, closes #4423, and fixes Brahman, Crypsis, Eater and Snowball which was not found by the community :wink: .

### CODE REVIEW

File: src/clj/game/core/actions.clj [hunk 1]
```diff
@@ -402,7 +402,8 @@
                 (dotimes [n times-pump]
                   (resolve-ability state side (dissoc pump-ability :cost :msg) (get-card state card) nil))
                 (doseq [sub (remove :broken (:subroutines current-ice))]
-                  (break-subroutine! state (get-card state current-ice) sub))
+                  (break-subroutine! state (get-card state current-ice) sub)
+                  (continue-ability state side (:additional-ability break-ability) (get-card state card) nil))
```
Comment (NoahTheDuke) [inline src/clj/game/core/actions.clj]: This can't use `continue-ability` cuz it'll complete the eid, and we don't want to complete it until later.

File: src/clj/game/core/ice.clj [hunk 2]
```diff
@@ -306,7 +306,10 @@
                                (wait-for (resolve-ability state side (make-eid state {:source-type :ability})
                                                           (break-subroutines-pay ice cost broken-subs args) card nil)
                                          (doseq [sub broken-subs]
-                                           (break-subroutine! state (get-card state ice) sub))
+                                           (break-subroutine! state (get-card state ice) sub)
+                                           (continue-ability state side (assoc (:additional-ability args)
```
Comment (NoahTheDuke) [inline src/clj/game/core/ice.clj]: Same here, can't use `continue-ability`, we have to have the `eid` available to complete later.

File: test/clj/game_test/cards/programs.clj [hunk 3]
```diff
@@ -2471,41 +2541,58 @@
...
+        (card-ability state :runner snow 1) ; match strength
+        (is (= 5 (:current-strength (refresh snow))) "Matched strength, gained 1")
+        (card-ability state :runner snow 0) ; strength matched, break a sub
+        (click-prompt state :runner "End the run")
+        (is (= 6 (:current-strength (refresh snow))) "Broke 1 sub, gained 1 more strength")
+        (run-continue state)
+        (is (= 5 (:current-strength (refresh snow))) "+4 until-end-of-run strength")
+        (run-jack-out state)
+        (is (= 1 (:current-strength (refresh snow))) "Back to default strength"))))
+  (testing "Strength boost until end of run when used to break a subroutine"
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/programs.clj]: Switch to "auto-pump"?

**Comment by NoahTheDuke** [comment]
This looks great! Just a couple small places for fixes, and then we'll be good go to!
