### PR TITLE
Make bin breakers use runner-install events. Fix Paladin reqs.

### LINKED ISSUE #5375: Paladin Poemu does not prompt for credit usage when bin breakers are installed from the bin
Loaded Paladin with 3 credits, run a code gate, black orchestra installs from the bin but no prompt to use Paladin credits to discount the install.

### PR DESCRIPTION
**Pull request by jwarwick**
Closes #5375

### CODE REVIEW

File: test/clj/game/cards/resources_test.clj [hunk 1]
```diff
@@ -3450,7 +3450,31 @@
...
+      (play-from-hand state :corp "Lotus Field" "HQ")
+      (rez state :corp (get-ice state :hq 0))
+      (take-credits state :corp)
+      (play-from-hand state :runner "Paladin Poemu")
+      (let [pp (get-resource state 0)]
+        (dotimes [_ 3]
+          (take-credits state :runner)
+          (take-credits state :corp))
+        (is (= 3 (get-counters (refresh pp) :credit)) "Paladin has 3c")
+        (changes-val-macro 0 (:credit (get-runner))
```
Comment (NoahTheDuke) [inline test/clj/game/cards/resources_test.clj:3468]: mind splitting this into a second line so the indentation doesn't go wild?
