### PR TITLE
Slot Machine Fix

### LINKED ISSUE #3923: Slot Machine reveals card advanced by third subroutine to runner
jnet reveal advanced card runner
jnet reveal advanced card
The face down card that you place 3 advancement counters on from the third subroutine is revealed to the runner.

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Cleaned up/fixed printing the wrong revealed cards and accidentally revealing the card the advancement tokens are placed on.

Closes #3923 and #3922

### CODE REVIEW

File: src/clj/game/cards/ice.clj [hunk 1]
```diff
@@ -2120,33 +2120,33 @@
...
+                    :effect (req (let [unique-types (top-3-types state)]
                                    (when (= 1 unique-types)
                                      (continue-ability
                                        state side
                                        {:choices {:req installed?}
                                         :prompt "Choose an installed card"
-                                        :effect (effect (system-msg (str "places 3 advancement tokens on "
-                                                                         (:title target)))
-                                                        (add-prop target :advance-counter 3 {:placed true}))}
+                                        :msg (msg "places 3 advancement tokens on "
```
Comment (Saintis) [inline src/clj/game/cards/ice.clj]:
```suggestion
                                        :msg (msg "place 3 advancement tokens on "
```

File: src/clj/game/cards/ice.clj [hunk 2]
```diff
@@ -2120,33 +2120,33 @@
...
-                                                   (join ", " (top-3-names runner)))))}]
+                                                   (join ", " (top-3-names state)))))}]
      :subroutines [{:label "Runner loses 3 [Credits]"
                     :msg "force the Runner to lose 3 [Credits]"
                     :effect (effect (lose-credits :runner 3))}
                    {:label "Gain 3 [Credits]"
-                    :effect (req (let [unique-types (top-3-types runner)]
+                    :effect (req (let [unique-types (top-3-types state)]
                                    (when (>= 2 unique-types)
                                      (system-msg state :corp (str "gains 3 [Credits]"))
```
Comment (Saintis) [inline src/clj/game/cards/ice.clj]: Should  move this logging to `:msg` as well.

File: src/clj/game/cards/ice.clj [hunk 3]
```diff
@@ -2120,33 +2120,33 @@
 
    "Slot Machine"
    (letfn [(name-builder [card] (str (:title card) " (" (:type card) ")"))
-           (top-3 [runner] (take 3 (:deck runner)))
-           (top-3-names [runner] (map name-builder (top-3 runner)))
-           (top-3-types [runner] (->> (top-3 runner) (map :type) (into #{}) count))]
+           (top-3 [state] (take 3 (get-in @state [:runner :deck])))
```
Comment (Saintis) [inline src/clj/game/cards/ice.clj]: Alternatively you could use `(take 3 (rest (:deck runner)))`, but reloading the deck from state is probably best.

Comment (NoahTheDuke) [reply src/clj/game/cards/ice.clj]: I thought of that, but it felt cleaner to do what I actually want to do, which is get the *actual* current deck. Felt a little too magical to have to remember that the deck has changed since binding `runner`. It made me wish for a `get-runner` function, like in tests, lol

File: src/clj/game/cards/ice.clj (hunk 2 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/ice.clj]: Good call

File: src/clj/game/cards/ice.clj (hunk 1 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/ice.clj]: Nice.

File: src/clj/game/cards/ice.clj (hunk 2 above)
Comment (NoahTheDuke) [reply src/clj/game/cards/ice.clj]: Now that I'm looking at the code, I'd done it this way cuz it felt redundant to do the check twice. I'll change the wording to achieve the same effect as a `:msg`.
