### PR TITLE
Fix the side check in card choice prompts

### LINKED ISSUE #1861: Runner "Knifed" card ends up in Corp archives
Somehow the runner card Knifed ended up in the corporation's archives after I used it to trash a barrier. 

---------------
ansichart started their turn 17 with 3  and 4 cards in their Grip.
ansichart spends  to draw a card.
ansichart spends  to draw a card.
ansichart spends  to gain 1 .
ansichart spends 1  and  to play Knifed.
ansichart uses D4v1d to break 1 subroutine.
Chewiedub has no further action.
Chewiedub trashes Wraparound.
ansichart continues the run.
Chewiedub rezzes Jackson Howard.
Chewiedub removes Jackson Howard from the game.
ansichart is ending their turn 17 with 3  and 5 cards in their Grip.
Chewiedub uses Jackson Howard to shuffle Knifed, Exchange of Information and 1 card into R&D.
Chewiedub started their turn 18 with 0  and 4 cards in HQ.
Chewiedub spends  to draw a card.
Chewiedub spends  to install a card in Server 7 (new remote).
Chewiedub spends  to gain 1 .
Chewiedub is ending their turn 18 with 1  and 5 cards in HQ.
ansichart started their turn 18 with 3  and 5 cards in their Grip.
ansichart spends  to make a run on Server 7.
Chewiedub has no further action.
ansichart steals Global Food Initiative and gains 2 agenda points.
ansichart spends  to gain 1 .
ansichart spends  to gain 1 .
ansichart spends 5  and  to play Sure Gamble.
ansichart uses Sure Gamble to gain 9 .
ansichart is ending their turn 18 with 9  and 4 cards in their Grip.
Chewiedub started their turn 19 with 1  and 5 cards in HQ.
Chewiedub spends  to play Exchange of Information.
Chewiedub uses Exchange of Information to swap Quantum Predictive Model for Global Food Initiative.
Chewiedub spends  to gain 1 .
Chewiedub spends  to gain 1 .
Chewiedub is ending their turn 19 with 3  and 5 cards in HQ.
ansichart started their turn 19 with 9  and 4 cards in their Grip.
ansichart spends  to gain 1 .
ansichart spends  to gain 1 .
ansichart spends  to gain 1 .
ansichart spends  to gain 1 .
ansichart is ending their turn 19 with 13  and 4 cards in their Grip.
Chewiedub started their turn 20 with 3  and 5 cards in HQ.

Chewiedub
lol how did i manage to get knifed in my deck

ansichart
lol

ansichart
I don't know

ansichart
funny glitch
Chewiedub spends  to draw a card.
Chewiedub spends  to install ICE protecting Server 8 (new remote).
Chewiedub spends  to gain 1 .

Chewiedub
can't trash it
Chewiedub trashes a card from their HQ.
Chewiedub is ending their turn 20 with 4  and 5 cards in HQ.
ansichart started their turn 20 with 13  and 4 cards in their Grip.
ansichart spends  to draw a card.
ansichart spends  to draw a card.

Chewiedub
its basically given the corp 1 brain damage
ansichart spends  to draw a card.
ansichart spends  to make a run on HQ.
Chewiedub rezzes Pop-up Window.
Chewiedub uses Pop-up Window to gain 1 .
ansichart sets credit to 12 (-1).
Chewiedub has no further action.
ansichart continues the run.
Chewiedub has no further action.
ansichart accesses Knifed.

Chewiedub
lol

ansichart
lol
---------------

### PR DESCRIPTION
**Pull request by erbridge**
Fixes #1861.

### CODE REVIEW

File: src/clj/game/cards/upgrades.clj [hunk 1]
```diff
@@ -135,7 +135,8 @@
    (letfn [(dhq [n i]
              {:req (req (pos? i))
               :prompt "Choose a card in HQ to add to the bottom of R&D"
-              :choices {:req #(and (:side % "Corp") (in-hand? %))}
+              :choices {:req #(and (= (:side % "Corp"))
```
Comment (nealterrell) [inline src/clj/game/cards/upgrades.clj]: Missed one here.

**Comment by mtgred** [comment]
👍
