### PR TITLE
fix Customized Secretary prompt not closing for the Corp

### LINKED ISSUE #6303: Customized secretary, when installed, tells the corp that the runner is taking an action when the runner has no prompt
On install of customized secretary, the corp gets a "runner is taking an action" prompt that persists even when the runner ends their turn, preventing the corp from beginning their next turn. This is solved by the corp manually using the /close-prompt command. The runner has no additional prompts on their screen.

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6303

### CODE REVIEW

File: src/clj/game/cards/programs.clj [hunk 1]
```diff
@@ -868,7 +867,8 @@
                   :waiting-prompt "Runner to make a decision"
                   :effect (req (let [from (take 5 (:deck runner))]
                                  (wait-for (reveal state side from)
-                                           (continue-ability state side (custsec-host from) card nil))))}
+                                           (continue-ability state side (custsec-host from) card nil)
+                                           (effect-completed state side eid))))}
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:871]: This is incorrect. Effect-completed should never be called after continue-ability; the ability being confused should call effect-completed.

File: src/clj/game/cards/programs.clj [hunk 2]
```diff
@@ -856,8 +856,7 @@
                :async true
                :effect (req (if (= target "Done")
                               (do (shuffle! state side :deck)
-                                  (system-msg state side "shuffles the stack")
-                                  (effect-completed state side eid))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:860]: This line needs to stay here. All branches of an async ability need to call effect-completed.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
The ability on line 851 when there are no programs is tagged as async but doesn't called effect-completed. Remove async and it'll work.

File: src/clj/game/cards/programs.clj [hunk 3]
```diff
@@ -850,7 +850,8 @@
             (if (empty? (filter program? cards))
               {:async true
                :msg "shuffle the stack"
-               :effect (effect (shuffle! :deck))}
+               :effect (req (shuffle! state side :deck)
+                            (effect-completed state side eid))}
```
Comment (NoahTheDuke) [inline src/clj/game/cards/programs.clj:854]: Because the ability only called system-msg, it doesn't need to be async, so remove this line and the :async true a couple lines above.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
