### PR TITLE
fix and test for district99 facedown card interaction

### LINKED ISSUE #4606: Trashing a Face down "Harbinger" adds a counter to "District 99"
"District 99" should only get a counter when a **program** or **hardware** is trashed, and face down runner cards are considered **type-less** so it shouldn't get a counter.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4606 

I have fixed interaction between District 99 and any facedown card. 
Proper fix would probably be somehow stripping types from facedown card. Something like:

get-type 
  if (facedown? empty else card types)

Not sure if this is possible :)

### CODE REVIEW

File: test/clj/game_test/cards/resources.clj [hunk 1]
```diff
@@ -936,7 +936,32 @@
...
+          (card-subroutine state :corp (refresh grim) 0)
+          (is (zero? (get-counters (refresh d99) :power)) "No power counters before Harbinger is trashed")
+          (click-card state :corp harb)
+          (is (= 1 (get-counters (refresh d99) :power)) "1 power counter after Harbinger trashed")
+          (run-jack-out state)
+          (take-credits state :corp)
+          (card-ability state :runner ap 0)
+          (click-card state :runner (get-runner-facedown state 0))
+          (is (= 1 (get-counters (refresh d99) :power)) "still 1 power counter after facedown Harbinger trashed")
+        ))))
```
Comment (lostgeek) [inline test/clj/game_test/cards/resources.clj]: Put all closed brackets on one line

**Comment by NoahTheDuke** [comment]
A general fix for the issue of the runner `type?` functions not checking that they're facedown would be to add a check to `facedown?` inside their definition, in `card.cljc`.

File: test/clj/game_test/cards/resources.clj [hunk 2]
```diff
@@ -936,7 +936,32 @@
           (click-prompt state :runner faerie)
           (is (= 1 (count (:hand (get-runner)))) "1 card added to hand")
           (is (= "Faerie" (-> (get-runner) :hand first :title)) "Faerie added to hand")
-          (is (zero? (get-counters (refresh d99) :power)) "Picking up Faerie removed 3 counters"))))))
+          (is (zero? (get-counters (refresh d99) :power)) "Picking up Faerie removed 3 counters")))))
+  (testing "Harbinger interaction, basic functionality"
+    (do-game
+      (new-game {:corp {:deck ["Grim"]}
+                 :runner {:deck ["District 99" "Harbinger" "Aesop's Pawnshop"]}})
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/resources.clj]:
```suggestion
                 :runner {:deck ["District 99" "Harbinger" "Aesop's Pawnshop"]}})
```
Please no trailing whitespace.
