### PR TITLE
fix #2291

### LINKED ISSUE #2291: Reaver/Wasteland requirements are slightly off
"Wasteland"
   {:events {:runner-trash {:req (req (and (first-event state :runner :runner-trash) (:installed target)))
                     :effect (effect (gain :credit 1))
                     :msg "to gain 1[Credit]"}}}

Steps to reproduce:
Have Faust
Have Reaver/Wasteland
Have Spy Cam
Boost Faust Str
Trash Spy Cam
-> No trigger

This seems to be because runner trashing a non-installed card (via Faust, other options exist) is the first runner-trash event.

### PR DESCRIPTION
**Pull request by danhut**
fix #2291

### CODE REVIEW

File: src/clj/game/core/rules.clj [hunk 1]
```diff
@@ -311,6 +311,7 @@
 (defn- resolve-trash
   [state side eid {:keys [zone type] :as card}
    {:keys [unpreventable cause keep-server-alive suppress-event] :as args} & targets]
+  (when (:installed card) (swap! state update-in [side :register :trashed-installed] (fnil inc 0)))
```
Comment (JoelCFC25) [inline src/clj/game/core/rules.clj]: Note that Corp cards never have `(:installed true)`. So if you want this to work equally well for both sides, it should be `(installed? card)` and you'll have to declare `installed?` up at the top of this file.
