### PR TITLE
Fix trap ice messing up with pass-ice

### LINKED ISSUE #6552: Bravado gives too many credits when interacting with Trap ice
Witnessed in an Ob game: Bravado on special offer, special offer trashes itself, runner gains 7. The ice was not passed, so it should be 6.

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6552

### CODE REVIEW

File: src/clj/game/cards/ice.clj [hunk 1]
```diff
@@ -575,7 +575,6 @@
                                                 (str/join ", " (map :title (take 3 (:deck runner))))
                                                 " from the Runner's Stack"))
                                (wait-for (mill state :corp :runner 3)
-                                         (system-msg state side (str "trashes Aimor"))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/ice.clj:578]: Reason for this? Seems relevant for tracking what's happening.

Comment (francescopellegrini) [reply src/clj/game/cards/ice.clj:578]: You're right, I was misled by the fact Aimor was the only trap ice logging its own trashing.

I found out there might be room for improvement in this area, so I'd like to work on it a bit more
