### PR TITLE
Nero ability fix

### LINKED ISSUE #4731: Nero automatically jacks out on encountering sentry
As soon as runner clicks to encounter ICE they jack out. Nero should be a choice, and can be other than the first encounter.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4731 

Nero ability is now optional and can be triggered only once per turn. New test cases.

### CODE REVIEW

File: src/clj/game/cards/identities.clj [hunk 1]
```diff
@@ -1051,12 +1051,14 @@
 
    "Nero Severn: Information Broker"
    {:events [{:event :encounter-ice
-              :req (req (has-subtype? target "Sentry"))
-              :interactive (req true)
-              :once :per-turn
-              :msg "jack out"
-              :async true
-              :effect (effect (jack-out eid))}]}
+              :optional {
```
Comment (NoahTheDuke) [inline src/clj/game/cards/identities.clj]: Can you move the `{` to the beginning of the next line and then line everything up so it's just indented 1 space? As seen in the New Angeles Sol implementation below.

**Comment by NoahTheDuke** [comment]
This looks great! Thank you so much!

File: src/clj/game/cards/identities.clj [hunk 2]
```diff
@@ -1051,12 +1051,13 @@
...
-              :interactive (req true)
-              :once :per-turn
-              :msg "jack out"
-              :async true
-              :effect (effect (jack-out eid))}]}
+              :optional 
+              {:req (req (and (not-used-once? state {:once :per-turn} card)
+                              (has-subtype? target "Sentry")))
+               :prompt "Do you want to jack out?"
+               :yes-ability {:once :per-turn
```
Comment (NoahTheDuke) [inline src/clj/game/cards/identities.clj]: This needs `:async true`

Comment (Kubik161) [reply src/clj/game/cards/identities.clj]: inside yes-ability?

Comment (NoahTheDuke) [reply src/clj/game/cards/identities.clj]: Yeah, cuz `jack-out` uses the `eid`.
