### PR TITLE
Fix: Pay moon pool RFG cost even if no cards are discarded

### LINKED ISSUE #6483: Moon Pool Doesn't RFG if No cards are trashed from HQ
As in title.  If corp chooses to trash zero cards from HQ with Moon Pool (so they can shuffle cards already in archives), it stays on the board instead of rfging as it should.

### PR DESCRIPTION
**Pull request by artemmikhalitsin**
Fixes #6483 

now the child ability has the :cancel-effect, so cost can still be paid

### CODE REVIEW

File: src/clj/game/cards/assets.clj [hunk 1]
```diff
@@ -1385,21 +1385,27 @@
...
-                              :max 2}
-                    :msg (msg "trash " (count targets) " cards from HQ ")
-                    :effect (req (wait-for (trash-cards state :corp targets {:cause-card card})
-                                           (continue-ability
-                                             state side
-                                             moon-pool-reveal-ability
-                                             card nil)))
-                    :cancel-effect (effect (system-msg "declines to use Moon Pool to trash any cards from HQ")
-                                           (continue-ability moon-pool-reveal-ability card nil))}]})))
+      (let [moon-pool-discard-ability
```
Comment (NoahTheDuke) [inline src/clj/game/cards/assets.clj:1388]: There's no need for a second let block, move this into the enclosing let block.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]

File: src/clj/game/cards/assets.clj (hunk 1 above)
Comment (artemmikhalitsin) [reply src/clj/game/cards/assets.clj:1388]: Thanks, I agree. It was a remnant of when I was messing with letfn

**Review by NoahTheDuke — APPROVED** [review]
