### PR TITLE
Tackling a few of the trivial bugs

### LINKED ISSUE #6935: Direct Access & Azmari EdTech
Looks like playing Direct Access as your first event doesn't "eat up" Azmari's trigger. Playing Sure Gamble after Direct Access still gives Azmari credits, which I think is not how it's supposed to be as Gamble isn't the first event, even if Azmari didn't see the Direct Access.

### LINKED ISSUE #7337: Cards on Cupellation Still Not Disabled
Link to bug replay: https://jinteki.net/bug-report/20fde847-35e7-4c37-bbf5-82e947e08762?b=0

Description:

Cards on Cupellation still aren't disabled (in replay Front Company is still active and Warden Fatuma cannot be rezzed because there's another active copy).  I think this was supposed to be fixed by #7326 but if I'm reading github correctly that went out in the last update and they still aren't disabled.  (Apologies if this is fixed and just hasn't made it live yet).

### LINKED ISSUE #7338: Message order when Tributary fires all subs is wrong
Link to bug replay: https://jinteki.net/bug-report/48d85877-9d59-4212-92a7-b35f85a500d7?b=0

Description:

When the Runner chooses not to break subroutines on Tributary, and the Corp fires all of them, the messages display in the following order:

> Corp uses Tributary to draw 1 card.
>
> Corp uses Tributary to give +2 strength to each piece of ice for the remainder of the run.
>
> Corp resolves 2 unbroken subroutines on Tributary ("[sub] Draw 1 card and install a piece of ice from HQ protecting another server" and "[sub] Give +2 strength to each piece of ice for the remainder of the run").
>
> Corp pays 0[c] to install ice protecting Server n.

In other words, the second subroutine, and the "resolves subroutines" message, display as having happened before the first is fully resolved (and because the wait for the Corp to decide happens in the middle of the message sequence, it looks to the Runner like the Corp chose not to install, until suddenly the install happens after the Runner thought the encounter was over.

### LINKED ISSUE #7359: Basic Trash Resource Action can target invalid cards
Link to bug replay: https://jinteki.net/bug-report/3a0ee984-fa54-4c5e-85d0-2d25464df582?b=0

Description:

Noticed with Cataloguer while spectating a game, noticed can also trash the Runner's ID while replicating. But not all cards. Might only be RWR cards?

### LINKED ISSUE #7365: TPTB + Stoke + Marrow interaction is broken
If you score an agenda with The Powers That Be on board, install a Stoke the Embers with it and resolve Stoke's optional clause (2nd paragraph), it somehow conflicts with Marrow, saying that Marrow placed an advancement counter on a card, and hanging the game. Runner sees a prompt 'waiting for a Corp trigger', while the Corp sees the opposite prompt. Double /close-prompt allows the game to continue, but the Marrow sabotage never happens.

### LINKED ISSUE #7367: [EDITME] Please give a short description of your bug here
Link to bug replay: https://jinteki.net/bug-report/51cb8b99-5703-42a9-a491-674fa4bff9a0?b=0

Description:

[EDITME] Please describe the steps to reproduce your bug and the resulting effect here.

The runner used Spree to move a Botulus off of Tributary before clicking on the Tributary move prompt. This causes a visual bug where the Tributary briefly appears to have a duplicated Botulus on it.

### LINKED ISSUE #7391: Cohort Guidance Program and DBS
Link to bug replay: https://jinteki.net/bug-report/f9757824-94b8-4e19-a05f-69fdcdfdae14?b=0

Description:

When you trigger cohort guidance program (draw 1 gain 2) with daily business show installed at start of turn you get your mandatory draw before making the DBS decision.  Additionally, if you additionally have warm reception installed, it doesn't let you chose the DBS trigger, and locks up if you try to proceed with warm reception.  You can get past this /close-prompt, but it strands the DBS cards in the set-aside zone.

### LINKED ISSUE #7394: The Holo Man text inaccuracy
Using The Holo Man does not print "Spend :click:" to the log, it should. Functionally I think this card works though.

Quote:
Corp uses The Holo Man in Server 5 to place 3 advancement counters on a card in Server 5.

Should read

Corp spends ⌚ to use The Holo Man in Server 5 to place 3 advancement counters on a card in Server 5.

### LINKED ISSUE #7399: Trash Action Bug
https://discord.com/channels/425105101451952128/425105101451952130/1230430274207354933

image-5

It seems as if you can trash any(?) card with the "Trash a resources if tagged" basic action.

### LINKED ISSUE #7405: Descent doesn't cost a credit to use it's expend ability.
Descent's expend ability should cost the corp a click and a credit, but at the moment, only a click is spent. 

Can be reproduced with Nuvem (when I had it occur), and an example is on The Metropole Grid's Smash & Grab stream at around 3:03:00 (Steve vs Nuvem SA) .

### LINKED ISSUE #7416: Descent does not charge me a credit to use expend ability
Link to bug replay: https://jinteki.net/bug-report/8a6046e7-22bf-4536-a22f-3cabbc025a4e?b=0

Description:

Descent does not charge me a credit to use expend ability.

### LINKED ISSUE #7419: Muse + LilyPAD ordering choice is missing
Muse tutor and LilyPAD draw happen at the same moment, but jnet doesn't give you a choice what to trigger first. Currently LilyPAD always resolves first.

### LINKED ISSUE #7430: Corporate town should queue itself at the start of turn
I think nobody has played this card for like 10 years, so we just never made this change

### LINKED ISSUE #7435: Keros is fizzled if the corp derezzes an ice first
as per title

### LINKED ISSUE #7437: Wage Workers continues to be active when hosted on Cuppelation
Link to bug replay: https://jinteki.net/bug-report/42263177-5f5f-4acd-8848-2046dc5a0d7e?b=0

Description:

Repro:
1. Host rezzed wage workers on cuppelation
2. Have corp click for credits 3 times

### LINKED ISSUE #7446: Hearts and Minds moving nonexistent counters
If you choose a card with 0 advancement counters to move a counter off with the 1st paragraph on Hearts and Minds, it then produces a counter on the card you choose afterwards anyways.

### LINKED ISSUE #7450: "Trash Resource" from corp enables trashing a program
Link to bug replay: https://jinteki.net/bug-report/aa5a8b1d-d47f-4fa5-a46f-34e4b1e83a0f?b=1

Description:

[EDITME] We arrived at a situation where the corp could trash a program (AUMAKUA) while using their "trash resource" command while the runner is tagged.

Corp was using the System Gateway Booster deck.
Runner was running a custom Anarch deck
Format was casual.

### LINKED ISSUE #7488: Log: Holo Man paid ability doesn't list the click + credit cost
image
See image. Should say that the player "spends 4c and {click} to use The Holo Man to"

### PR DESCRIPTION
**Pull request by NBKelly**
Closes #7337, Closes #7437 (we were applying modifiers to the card, rather than the target)
Closes #7446 (just needed `pos?` added to the query)
Closes #7435 (didn't check source of first-event?)
Closes #7430 (reformatted the card like we do PAD campaign)
Closes #7419 (added `:interactive (req true)` to muse)
Closes #7416 and Closes #7405 (I think this got "fixed", then we updated costs while this fix was pending, and then it was no longer fixed)
Closes #7399, Closes #7359, Closes #7450 (basic trash action didn't always assert the target was a resource)
Closes #7394, Closes #7488 (just moved the check into a function, and the message into a `:msg` block)
Closes #7391 (interior ability used wait-for without having an `:async true` on it)
Closes #7367 (Tributary now uses the freshest version of itself when moving. This only effects an illegal scenario anyway, but it is what it is)
Closes #7365 (second ability used wait-for without having an `:async true` tag)
Closes #7338 (interior ability was missing an `:async true` tag)
Closes #6935 (Azmari actually checks it's the first event now)

### CODE REVIEW

File: src/clj/game/cards/basic.clj [hunk 1]
```diff
@@ -111,8 +111,9 @@
                                                   (< 1 (->> (all-active-installed state :runner)
                                                             (filter resource?)
                                                             count)))
-                                           (resource? target)
+                                           true
```
Comment (NoahTheDuke) [inline src/clj/game/cards/basic.clj:114]: No reason for this to be here, lol.

Comment (NoahTheDuke) [reply src/clj/game/cards/basic.clj:114]: Oh wait, is this in the `if` check? nevermind.

**Comment by NoahTheDuke** [comment]
Resolve the conflict and this is good for merging.
