### PR TITLE
Print choices and additional costs in Game Log

### LINKED ISSUE #4102: Insufficient logging for Fully Operational
Fully Operational does not say which choices the Corp makes.

### LINKED ISSUE #4104: Khusyuk says the wrong number named in game log
If you choose 2c, and you have 5 2c cards on the table, the game log will say that you chose 5c as your target.

### LINKED ISSUE #4109: Whistleblower doesn't print chosen agenda
Whistleblower doesn't print to the game log what agenda was chosen.

### LINKED ISSUE #4110: Climactic Showdown doesn't print chosen server
Climactic Showdown doesn't print to the game log the chosen server that the Corp has to trash an ice from.

### LINKED ISSUE #4112: Isolation doesn't print chosen resource
Isolation does not say which resource the Runner trashes.

### LINKED ISSUE #4123: Khusyuk writes numbers accessed instead of credits chosen in console, and "top" number missing
When runner selected 1 credit install cost on Khusyuk, things worked as it should, but the text in console was wrong: it said <runner> chooses an install cost of 6 [c] and reveals (top:) <card1>,<card2>...

image

It should be

<runner> chooses an install cost of **1** [c] and reveals (top:**6**) <card1>,<card2>...

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Fixes #4110 
Fixes #4109 
Fixes #4104  
Fixes #4102 
Fixes #4112 
Fixes #4123

### CODE REVIEW

File: src/clj/game/cards/operations.clj [hunk 1]
```diff
@@ -753,7 +753,7 @@
                                                            card nil))))}))]
      {:async true
       :effect (effect (system-msg (str "uses Fully Operational to make "
-                                       (count (full-servers state)) " gain/draw decisions"))
+                                       (inc (count (full-servers state))) " gain/draw decisions"))
```
Comment (Saintis) [inline src/clj/game/cards/operations.clj]: Probably want to use `quantify` here for the number of decisions.
