### PR TITLE
Tranqulity Home Grid interaction with ICE fix

### LINKED ISSUE #4721: Installing ice protecting the server turns off Tranquility Home Grid
Tranquility Home Grid  is rezzed and click one I installed an ice protecting that remote server. Click two i installed an agenda in the remote with tranquility. It should fire but it didn't. I think it might be a bug.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4721

### CODE REVIEW

File: src/clj/game/cards/upgrades.clj [hunk 1]
```diff
@@ -1407,7 +1407,8 @@
                                  (agenda? target)
                                  (upgrade? target))
                              (= (second (:zone card)) (second (:zone target)))
-                             (first-event? state :corp :corp-install #(= (-> card :zone second) (-> % first :zone second)))))
+                             (first-event? state :corp :corp-install #(and (= (-> card :zone second) (-> % first :zone second))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/upgrades.clj]: This seems like a good place to use `in-server?` instead of manually checking the `:zone`.

Comment (Kubik161) [reply src/clj/game/cards/upgrades.clj]: Feel free to correct me :) I was trying to use in-same-server? but was unable to make it work :)

Comment (NoahTheDuke) [reply src/clj/game/cards/upgrades.clj]: Huh! If it's not working, then something has gone wrong. I'll take a look.
