### PR TITLE
Emergent creativity prompt fix

### LINKED ISSUE #4604: Emergent Creativity can Install Resources
When Creativity searches the stack for programs/hardware, the box that pop's up has all installable cards in it instead of just programs and hardware.

### PR DESCRIPTION
**Pull request by Kubik161**
Closes #4604

### CODE REVIEW

File: test/clj/game_test/cards/events.clj [hunk 1]
```diff
@@ -1671,20 +1671,31 @@
...
+      (is (= 2 (:click (get-runner))) "Emergent Creativity is a Double event")))
+  (testing "Resource not shown in prompt"
+    (do-game
+      (new-game {:runner {:deck ["Emergent Creativity" "Heartbeat" "Gordian Blade" "Liberated Account"]}})
+      (starting-hand state :runner ["Emergent Creativity" "Heartbeat" "Gordian Blade" ])
+      (take-credits state :corp)
+      (play-from-hand state :runner "Emergent Creativity")
+      (click-card state :runner (find-card "Heartbeat" (:hand (get-runner))))
+      (click-card state :runner (find-card "Gordian Blade" (:hand (get-runner))))
+      (is (= 1 (-> (get-runner) :prompt first :choices count)) "Liberated Account shouldn't be shown in prompt (only Cancel)")
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/events.clj]: Can you switch this to something like `(= ["Cancel"] (-> (get-runner) :prompt first :choices))`? That way, we have a clear understanding of what's being checked, and a change in the prompts will make this fail instead of silently passing (because we're only counting quantity).

File: test/clj/game_test/cards/events.clj [hunk 2]
```diff
@@ -1671,20 +1671,31 @@
...
+      (is (zero? (count (:deck (get-runner)))) "Installed from heap")
+      (is (= 3 (count (:discard (get-runner)))) "Discard is 3 cards - EC, Heartbeat, GB")
+      (is (= 2 (:click (get-runner))) "Emergent Creativity is a Double event")))
+  (testing "Resource not shown in prompt"
+    (do-game
+      (new-game {:runner {:deck ["Emergent Creativity" "Heartbeat" "Gordian Blade" "Liberated Account"]}})
+      (starting-hand state :runner ["Emergent Creativity" "Heartbeat" "Gordian Blade" ])
+      (take-credits state :corp)
+      (play-from-hand state :runner "Emergent Creativity")
+      (click-card state :runner (find-card "Heartbeat" (:hand (get-runner))))
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/events.clj]:
```suggestion
      (click-card state :runner "Heartbeat")
```

File: test/clj/game_test/cards/events.clj [hunk 3]
```diff
@@ -1671,20 +1671,31 @@
...
+      (click-card state :runner (find-card "Gordian Blade" (:hand (get-runner))))
```
Comment (NoahTheDuke) [inline test/clj/game_test/cards/events.clj]:
```suggestion
      (click-card state :runner "Gordian Blade")
```

File: test/clj/game_test/cards/events.clj (hunk 1 above)
Comment (Kubik161) [reply test/clj/game_test/cards/events.clj]: Sure, I will fix it
