### PR TITLE
Fix Rebirth and DJ Fenris, and simplify prompt handling

### LINKED ISSUE #4672: Broken Rebirth and DJ Fenris prompts
Rebirth and DJ Fenris prompts no longer work. This issue was introduced by #4645

### PR DESCRIPTION
**Pull request by ouroboros8**
The front-end now only passes card titles to the backend when a prompt
with a choice of cards is clicked. The backend then compares this title
against the titles of the cards in the prompt hash-map.

Resolves #4672

### CODE REVIEW

File: src/clj/game/core/actions.clj [hunk 1]
```diff
@@ -250,20 +247,14 @@
...
-                            choices)
-            button (first buttons)]
-        (if button
-          (do (when-let [effect-prompt (:effect prompt)]
-                (effect-prompt button))
+      (let [match (first (filter #(or (= choice %)
+                                       (= choice (:title % "")))
+                                  choices))]
+        (if match
+          (do ((:effect prompt) match)
```
Comment (NoahTheDuke) [inline src/clj/game/core/actions.clj]: Not all prompts will have effects, so you'll want to leave the `when-let` in.

Comment (ouroboros8) [reply src/clj/game/core/actions.clj]: Huh. If there's no effect in the default case does the prompt just do nothing?

Comment (NoahTheDuke) [reply src/clj/game/core/actions.clj]: You're right, I was thinking of a different part of the engine. Please ignore me.

File: src/clj/game/core/actions.clj [hunk 2]
```diff
@@ -250,20 +247,14 @@
...
-                                                    (lower-case (:title choice "do-not-match")))]
-                                   (or (= choice-str (lower-case %))
-                                       (= choice-str (lower-case (:title % ""))))))
-                            choices)
-            button (first buttons)]
-        (if button
-          (do (when-let [effect-prompt (:effect prompt)]
-                (effect-prompt button))
+      (let [match (first (filter #(or (= choice %)
+                                       (= choice (:title % "")))
```
Comment (NoahTheDuke) [inline src/clj/game/core/actions.clj]:
```suggestion
                                      (= choice (:title % "")))
```
