### PR TITLE
FIX: :no-trash-or-steal shouldn't increment in Archives

### LINKED ISSUE #3388: Maw not triggering
Just flagging up a case when Maw didn't trigger when it should have.

Situation:

Alice as the ID with Maw and Archives Interface installed does something on her side of the board for a couple of clicks, then runs archives third click. The Corp trashes an Obokata to her ability and she accesses archives seeing, but not stealing, the Obokata in the bin and removing from game some other card with Archives Interface. Then last click she runs HQ, accessing the sole card in HQ, another Obokata which she declines to steal. As the first card accessed not in Archives for the turn, this should have triggered Maw to send it to the bin, but it didn't trigger.

They're the cards I remember that seem relevant, hope that is helpful!

### PR DESCRIPTION
**Pull request by NoahTheDuke**
We were incrementing `:no-trash-or-steal` when accessing cards in Archives, and while I could hear an argument for it needing to increment in that case because you can technically decline to steal agendas in Archives with additional steal costs, this system only exists for Maw and I'm only interested in fixing it right now.

Fixes #3388

### CODE REVIEW

File: src/clj/game/core/runs.clj [hunk 1]
```diff
@@ -44,7 +44,9 @@
   (when (and (is-type? c "Agenda")
              (not (find-cid (:cid c) (get-in @state [:runner :scored]))))
     (trigger-event state side :no-steal c))
-  (when (get-card state c)
+  (when (and (get-card state c)
+             ;; Don't increment :no-trash-or-steal if accessing a card in Archives
+             (not (find-cid (:cid c) (get-in @state [:corp :discard]))))
```
Comment (nealterrell) [inline src/clj/game/core/runs.clj]: Can this be done a little more directly, like checking the zone of `c`? Also, couldn't we predicate this on `c` not being an agenda?

Comment (NoahTheDuke) [reply src/clj/game/core/runs.clj]: Yeah, checking the zone is better. Forgot about that.

We still want it increment when you see an agenda, as that's what Maw looks for. Otherwise, declining to steal an agenda with an additional cost won't trigger Maw.
