### PR TITLE
Bug fixes 22-07-28

### LINKED ISSUE #6488: Cannot trash Public Agendas with Ob Superheavy ability available
Attempting to trash Oaktown Renovation causes an Internal Error. Fails both through card abilities (ie. Stavka, Extract) and Drag+Drop or /trash. Have done a bit of testing and it seems to happen with all Public Agendas. 

I'm guessing it hangs because it doesn't know what to do with a non-rezzed+non-derezzed card, or the agenda is seen as rezzed but doesn't have a rez cost.

There is no issue if the Ob trigger has already been fired that turn though.

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Closes #6488

### CODE REVIEW

File: src/clj/game/cards/operations.clj [hunk 1]
```diff
@@ -549,7 +549,7 @@
   {:on-play
    {:prompt "Choose a faceup card"
     :choices {:card #(or (and (corp? %)
-                              (rezzed? %))
+                              (faceup? %))
```
Comment (artemmikhalitsin) [inline src/clj/game/cards/operations.clj:552]: This lets you dedi cards in archives

**Review by artemmikhalitsin — CHANGES_REQUESTED** [review]

File: src/clj/game/cards/operations.clj (hunk 1 above)
Comment (artemmikhalitsin) [inline src/clj/game/cards/operations.clj:552]:
```suggestion
                               (installed? %)
                               (faceup? %))
```
Otherwise you can dedi cards in archives lol

**Comment by artemmikhalitsin** [comment]
Just tried it out in a game and oaktown installs face-down

File: src/clj/game/cards/operations.clj (hunk 1 above)
Comment (artemmikhalitsin) [reply src/clj/game/cards/operations.clj:552]: Looking at the wording on a few cards (Dedi, Mumbad Construction Co.), it seems "faceup" implies "installed", unless otherwise specified.
