### PR TITLE
Fix The Root cannot pay for advancing cards

### LINKED ISSUE #6714: The Root does trigger when advancing
The Root does not trigger to discount the basic action when it still has recurring credits left on it

### PR DESCRIPTION
**Pull request by francescopellegrini**
Fixes #6714

### CODE REVIEW

File: src/clj/game/cards/basic.clj [hunk 1]
```diff
@@ -82,14 +84,13 @@
...
                 :msg (msg "advance " (card-str state target))
-                :req (req (can-advance? state side target))
-                :effect (effect (update-advancement-requirement target)
-                                (add-prop (get-card state target) :advance-counter 1)
-                                (play-sfx "click-advance")
-                                (effect-completed eid))}
+                :req (req (and (can-advance? state side target)
+                               (can-pay? state side
+                                         (assoc eid :source :action :source-type :advance)
+                                         card nil [:credit 1 :click 1])))
```
Comment (NoahTheDuke) [inline src/clj/game/cards/basic.clj:92]: Does this cover when there are additional costs on the click ability?

Comment (francescopellegrini) [reply src/clj/game/cards/basic.clj:92]: Can you make an example of a card creating additional costs on the click ability? I couldn't find any.. :/

Comment (NoahTheDuke) [reply src/clj/game/cards/basic.clj:92]: [Enhanced Login Protocol](https://netrunnerdb.com/en/card/06022) changes the cost of a basic action:

> As an additional cost to take the basic action to run a server for the first time each turn, the Runner must spend click.

It's true that a card doesn't exist that changes the "advance a card" basic action. But we should still be writing abilities like those cards do exist.

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
